from __future__ import annotations

from importlib import import_module


LEGACY_PATTERN_FORMULA_PREFIX = "src.factor.assets.pattern_factors.factors."
DOMAIN_PATTERN_FORMULA_PREFIX = "src.domain.pattern_factor_formulas."


def normalize_pattern_module_name(module_name: str) -> str:
    if module_name.startswith(DOMAIN_PATTERN_FORMULA_PREFIX):
        return module_name
    if module_name.startswith(LEGACY_PATTERN_FORMULA_PREFIX):
        return module_name.replace(LEGACY_PATTERN_FORMULA_PREFIX, DOMAIN_PATTERN_FORMULA_PREFIX, 1)
    return module_name


def load_pattern_factor_function(module_name: str, function_name: str):
    module = import_module(normalize_pattern_module_name(module_name))
    return getattr(module, function_name)


def get_pattern_factor_category(factor_name: str) -> str:
    module_name = normalize_pattern_module_name(PATTERN_FACTOR_LIST[factor_name]["module"])
    marker = DOMAIN_PATTERN_FORMULA_PREFIX
    if marker not in module_name:
        raise ValueError(f"无法从 module 路径解析K线形态因子分类: {module_name}")
    return module_name.split(marker, maxsplit=1)[1].split(".", maxsplit=1)[0]


# 形态类因子注册表。
# 这里先独立建表，后续新增 CDL / 事件型 K 线形态时直接往这里加。
PATTERN_FACTOR_LIST: dict[str, dict[str, object]] = {
    "cdl2crows": {
        "label": "两只乌鸦Two Crows",
        "formula": (
            "Pattern(i,t) = -1 if Three-candle Two Crows bearish reversal is detected on day t, else 0"
        ),
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.two_crows.cdl2crows",
        "function": "compute_cdl2crows",
        "output_columns": ["cdl2crows"],
        "factor_type": "kline_pattern",
    },
    "cdl3blackcrows": {
        "label": "三只乌鸦Three Black Crows",
        "formula": "Pattern(i,t) = -1 if Three Black Crows bearish reversal is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.three_black_crows.cdl3blackcrows",
        "function": "compute_cdl3blackcrows",
        "output_columns": ["cdl3blackcrows"],
    },
    "cdl3inside": {
        "label": "三内部上涨下跌Three Inside Up/Down",
        "formula": "Pattern(i,t) = 1 for bullish Three Inside Up, -1 for bearish Three Inside Down, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.three_inside.cdl3inside",
        "function": "compute_cdl3inside",
        "output_columns": ["cdl3inside"],
    },
    "cdl3linestrike": {
        "label": "三线打击Three-Line Strike",
        "formula": "Pattern(i,t) = 1 for bullish Three-Line Strike, -1 for bearish Three-Line Strike, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.three_line_strike.cdl3linestrike",
        "function": "compute_cdl3linestrike",
        "output_columns": ["cdl3linestrike"],
    },
    "cdl3starsinsouth": {
        "label": "南方三星Three Stars In The South",
        "formula": "Pattern(i,t) = 1 if bullish Three Stars In The South is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.three_stars_in_the_south.cdl3starsinsouth",
        "function": "compute_cdl3starsinsouth",
        "output_columns": ["cdl3starsinsouth"],
    },
    "cdl3whitesoldiers": {
        "label": "三白兵Three Advancing White Soldiers",
        "formula": "Pattern(i,t) = 1 if bullish Three Advancing White Soldiers is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.three_white_soldiers.cdl3whitesoldiers",
        "function": "compute_cdl3whitesoldiers",
        "output_columns": ["cdl3whitesoldiers"],
    },
    "cdlabandonedbaby": {
        "label": "弃婴Abandoned Baby",
        "formula": "Pattern(i,t) = 1 for bullish Abandoned Baby, -1 for bearish Abandoned Baby, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.abandoned_baby.cdlabandonedbaby",
        "function": "compute_cdlabandonedbaby",
        "output_columns": ["cdlabandonedbaby"],
    },
    "cdladvanceblock": {
        "label": "推进受阻Advance Block",
        "formula": "Pattern(i,t) = -1 if bearish Advance Block is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.advance_block.cdladvanceblock",
        "function": "compute_cdladvanceblock",
        "output_columns": ["cdladvanceblock"],
    },
    "cdlbelthold": {
        "label": "捉腰带线Belt-hold",
        "formula": "Pattern(i,t) = 1 for bullish Belt-hold, -1 for bearish Belt-hold, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.belt_hold.cdlbelthold",
        "function": "compute_cdlbelthold",
        "output_columns": ["cdlbelthold"],
    },
    "cdlbreakaway": {
        "label": "脱离Breakaway",
        "formula": "Pattern(i,t) = 1 for bullish Breakaway, -1 for bearish Breakaway, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.breakaway.cdlbreakaway",
        "function": "compute_cdlbreakaway",
        "output_columns": ["cdlbreakaway"],
    },
    "cdlclosingmarubozu": {
        "label": "收盘光头光脚Closing Marubozu",
        "formula": "Pattern(i,t) = 1 for bullish Closing Marubozu, -1 for bearish Closing Marubozu, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.closing_marubozu.cdlclosingmarubozu",
        "function": "compute_cdlclosingmarubozu",
        "output_columns": ["cdlclosingmarubozu"],
    },
    "cdlconcealbabyswallow": {
        "label": "隐藏吞没婴儿Concealing Baby Swallow",
        "formula": "Pattern(i,t) = 1 if bullish Concealing Baby Swallow is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.concealing_baby_swallow.cdlconcealbabyswallow",
        "function": "compute_cdlconcealbabyswallow",
        "output_columns": ["cdlconcealbabyswallow"],
    },
    "cdlcounterattack": {
        "label": "反击线Counterattack",
        "formula": "Pattern(i,t) = 1 for bullish Counterattack, -1 for bearish Counterattack, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.counterattack.cdlcounterattack",
        "function": "compute_cdlcounterattack",
        "output_columns": ["cdlcounterattack"],
    },
    "cdldarkcloudcover": {
        "label": "乌云盖顶Dark Cloud Cover",
        "formula": "Pattern(i,t) = -1 if bearish Dark Cloud Cover is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.dark_cloud_cover.cdldarkcloudcover",
        "function": "compute_cdldarkcloudcover",
        "output_columns": ["cdldarkcloudcover"],
    },
    "cdldoji": {
        "label": "十字Doji",
        "formula": "Pattern(i,t) = 1 if Doji is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.doji.cdldoji",
        "function": "compute_cdldoji",
        "output_columns": ["cdldoji"],
    },
    "cdldojistar": {
        "label": "十字星Doji Star",
        "formula": "Pattern(i,t) = 1 for bullish Doji Star, -1 for bearish Doji Star, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.doji_star.cdldojistar",
        "function": "compute_cdldojistar",
        "output_columns": ["cdldojistar"],
    },
    "cdldragonflydoji": {
        "label": "蜻蜓十字Dragonfly Doji",
        "formula": "Pattern(i,t) = 1 if Dragonfly Doji is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.dragonfly_doji.cdldragonflydoji",
        "function": "compute_cdldragonflydoji",
        "output_columns": ["cdldragonflydoji"],
    },
    "cdlengulfing": {
        "label": "吞没形态Engulfing",
        "formula": "Pattern(i,t) = 1 for bullish Engulfing, -1 for bearish Engulfing, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.engulfing.cdlengulfing",
        "function": "compute_cdlengulfing",
        "output_columns": ["cdlengulfing"],
    },
    "cdleveningdojistar": {
        "label": "黄昏十字星Evening Doji Star",
        "formula": "Pattern(i,t) = -1 if Evening Doji Star is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.evening_doji_star.cdleveningdojistar",
        "function": "compute_cdleveningdojistar",
        "output_columns": ["cdleveningdojistar"],
    },
    "cdleveningstar": {
        "label": "黄昏星Evening Star",
        "formula": "Pattern(i,t) = -1 if Evening Star is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.evening_star.cdleveningstar",
        "function": "compute_cdleveningstar",
        "output_columns": ["cdleveningstar"],
    },
    "cdlgapsidesidewhite": {
        "label": "并列白线Gap Side-by-Side White",
        "formula": "Pattern(i,t) = 1 for bullish gap side-by-side white lines, -1 for bearish variant, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.gap_side_by_side_white_lines.cdlgapsidesidewhite",
        "function": "compute_cdlgapsidesidewhite",
        "output_columns": ["cdlgapsidesidewhite"],
    },
    "cdlgravestonedoji": {
        "label": "墓碑十字Gravestone Doji",
        "formula": "Pattern(i,t) = -1 if Gravestone Doji is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.gravestone_doji.cdlgravestonedoji",
        "function": "compute_cdlgravestonedoji",
        "output_columns": ["cdlgravestonedoji"],
    },
    "cdlhammer": {
        "label": "锤头线Hammer",
        "formula": "Pattern(i,t) = 1 if Hammer is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.hammer.cdlhammer",
        "function": "compute_cdlhammer",
        "output_columns": ["cdlhammer"],
    },
    "cdlhangingman": {
        "label": "上吊线Hanging Man",
        "formula": "Pattern(i,t) = -1 if Hanging Man is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.hanging_man.cdlhangingman",
        "function": "compute_cdlhangingman",
        "output_columns": ["cdlhangingman"],
    },
    "cdlharami": {
        "label": "母子线Harami",
        "formula": "Pattern(i,t) = 1 for bullish Harami, -1 for bearish Harami, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.harami.cdlharami",
        "function": "compute_cdlharami",
        "output_columns": ["cdlharami"],
    },
    "cdlharamicross": {
        "label": "十字孕线Harami Cross",
        "formula": "Pattern(i,t) = 1 for bullish Harami Cross, -1 for bearish Harami Cross, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.harami_cross.cdlharamicross",
        "function": "compute_cdlharamicross",
        "output_columns": ["cdlharamicross"],
    },
    "cdlhighwave": {
        "label": "风高浪大线High-Wave",
        "formula": "Pattern(i,t) = 1 if High-Wave Candle is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.high_wave.cdlhighwave",
        "function": "compute_cdlhighwave",
        "output_columns": ["cdlhighwave"],
    },
    "cdlhikkake": {
        "label": "陷阱形态Hikkake",
        "formula": "Pattern(i,t) = 1 for bullish Hikkake, -1 for bearish Hikkake, else 0",
        "required_fields": ["high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.hikkake.cdlhikkake",
        "function": "compute_cdlhikkake",
        "output_columns": ["cdlhikkake"],
    },
    "cdlhikkakemod": {
        "label": "改良陷阱形态Modified Hikkake",
        "formula": "Pattern(i,t) = 1 for bullish Modified Hikkake, -1 for bearish Modified Hikkake, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.hikkake_modified.cdlhikkakemod",
        "function": "compute_cdlhikkakemod",
        "output_columns": ["cdlhikkakemod"],
    },
    "cdlhomingpigeon": {
        "label": "归巢鸽Homing Pigeon",
        "formula": "Pattern(i,t) = 1 if bullish Homing Pigeon is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.homing_pigeon.cdlhomingpigeon",
        "function": "compute_cdlhomingpigeon",
        "output_columns": ["cdlhomingpigeon"],
    },
    "cdlidentical3crows": {
        "label": "三胞胎乌鸦Identical Three Crows",
        "formula": "Pattern(i,t) = -1 if bearish Identical Three Crows is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.identical_three_crows.cdlidentical3crows",
        "function": "compute_cdlidentical3crows",
        "output_columns": ["cdlidentical3crows"],
    },
    "cdlinneck": {
        "label": "颈内线In-Neck",
        "formula": "Pattern(i,t) = -1 if bearish In-Neck Pattern is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.in_neck.cdlinneck",
        "function": "compute_cdlinneck",
        "output_columns": ["cdlinneck"],
    },
    "cdlinvertedhammer": {
        "label": "倒锤头Inverted Hammer",
        "formula": "Pattern(i,t) = 1 if bullish Inverted Hammer is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.inverted_hammer.cdlinvertedhammer",
        "function": "compute_cdlinvertedhammer",
        "output_columns": ["cdlinvertedhammer"],
    },
    "cdlkicking": {
        "label": "反冲形态Kicking",
        "formula": "Pattern(i,t) = 1 for bullish Kicking, -1 for bearish Kicking, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.kicking.cdlkicking",
        "function": "compute_cdlkicking",
        "output_columns": ["cdlkicking"],
    },
    "cdlkickingbylength": {
        "label": "长实体反冲Kicking by Length",
        "formula": "Pattern(i,t) = 1 for bullish Kicking by Length, -1 for bearish Kicking by Length, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.kicking_by_length.cdlkickingbylength",
        "function": "compute_cdlkickingbylength",
        "output_columns": ["cdlkickingbylength"],
    },
    "cdlladderbottom": {
        "label": "梯底Ladder Bottom",
        "formula": "Pattern(i,t) = 1 if bullish Ladder Bottom is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.ladder_bottom.cdlladderbottom",
        "function": "compute_cdlladderbottom",
        "output_columns": ["cdlladderbottom"],
    },
    "cdllongleggeddoji": {
        "label": "长脚十字Long Legged Doji",
        "formula": "Pattern(i,t) = 1 if Long Legged Doji is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.long_legged_doji.cdllongleggeddoji",
        "function": "compute_cdllongleggeddoji",
        "output_columns": ["cdllongleggeddoji"],
    },
    "cdllongline": {
        "label": "长蜡烛线Long Line",
        "formula": "Pattern(i,t) = 1 for bullish Long Line, -1 for bearish Long Line, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.long_line.cdllongline",
        "function": "compute_cdllongline",
        "output_columns": ["cdllongline"],
    },
    "cdlmarubozu": {
        "label": "光头光脚Marubozu",
        "formula": "Pattern(i,t) = 1 for bullish Marubozu, -1 for bearish Marubozu, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.marubozu.cdlmarubozu",
        "function": "compute_cdlmarubozu",
        "output_columns": ["cdlmarubozu"],
    },
    "cdlmatchinglow": {
        "label": "相同低点Matching Low",
        "formula": "Pattern(i,t) = 1 if bullish Matching Low is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.matching_low.cdlmatchinglow",
        "function": "compute_cdlmatchinglow",
        "output_columns": ["cdlmatchinglow"],
    },
    "cdlmathold": {
        "label": "铺垫Mat Hold",
        "formula": "Pattern(i,t) = 1 if bullish Mat Hold is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.mat_hold.cdlmathold",
        "function": "compute_cdlmathold",
        "output_columns": ["cdlmathold"],
    },
    "cdlmorningdojistar": {
        "label": "晨十字星Morning Doji Star",
        "formula": "Pattern(i,t) = 1 if bullish Morning Doji Star is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.morning_doji_star.cdlmorningdojistar",
        "function": "compute_cdlmorningdojistar",
        "output_columns": ["cdlmorningdojistar"],
    },
    "cdlmorningstar": {
        "label": "晨星Morning Star",
        "formula": "Pattern(i,t) = 1 if bullish Morning Star is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.morning_star.cdlmorningstar",
        "function": "compute_cdlmorningstar",
        "output_columns": ["cdlmorningstar"],
    },
    "cdlonneck": {
        "label": "颈上线On-Neck",
        "formula": "Pattern(i,t) = -1 if bearish On-Neck Pattern is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.on_neck.cdlonneck",
        "function": "compute_cdlonneck",
        "output_columns": ["cdlonneck"],
    },
    "cdlpiercing": {
        "label": "刺透形态Piercing",
        "formula": "Pattern(i,t) = 1 if bullish Piercing Pattern is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.piercing.cdlpiercing",
        "function": "compute_cdlpiercing",
        "output_columns": ["cdlpiercing"],
    },
    "cdlrickshawman": {
        "label": "黄包车夫Rickshaw Man",
        "formula": "Pattern(i,t) = 1 if Rickshaw Man is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.rickshaw_man.cdlrickshawman",
        "function": "compute_cdlrickshawman",
        "output_columns": ["cdlrickshawman"],
    },
    "cdlrisefall3methods": {
        "label": "上升下降三法Rising/Falling Three Methods",
        "formula": "Pattern(i,t) = 1 for bullish Rising Three Methods, -1 for bearish Falling Three Methods, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.rising_falling_three_methods.cdlrisefall3methods",
        "function": "compute_cdlrisefall3methods",
        "output_columns": ["cdlrisefall3methods"],
    },
    "cdlseparatinglines": {
        "label": "分离线Separating Lines",
        "formula": "Pattern(i,t) = 1 for bullish Separating Lines, -1 for bearish Separating Lines, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.separating_lines.cdlseparatinglines",
        "function": "compute_cdlseparatinglines",
        "output_columns": ["cdlseparatinglines"],
    },
    "cdlshootingstar": {
        "label": "流星线Shooting Star",
        "formula": "Pattern(i,t) = -1 if Shooting Star is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.shooting_star.cdlshootingstar",
        "function": "compute_cdlshootingstar",
        "output_columns": ["cdlshootingstar"],
    },
    "cdlshortline": {
        "label": "短蜡烛线Short Line",
        "formula": "Pattern(i,t) = 1 for bullish Short Line, -1 for bearish Short Line, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.short_line.cdlshortline",
        "function": "compute_cdlshortline",
        "output_columns": ["cdlshortline"],
    },
    "cdlspinningtop": {
        "label": "纺锤线Spinning Top",
        "formula": "Pattern(i,t) = 1 for bullish Spinning Top, -1 for bearish Spinning Top, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.spinning_top.cdlspinningtop",
        "function": "compute_cdlspinningtop",
        "output_columns": ["cdlspinningtop"],
    },
    "cdlstalledpattern": {
        "label": "停顿形态Stalled Pattern",
        "formula": "Pattern(i,t) = -1 if bearish Stalled Pattern is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.stalled_pattern.cdlstalledpattern",
        "function": "compute_cdlstalledpattern",
        "output_columns": ["cdlstalledpattern"],
    },
    "cdlsticksandwich": {
        "label": "条形三明治Stick Sandwich",
        "formula": "Pattern(i,t) = 1 if bullish Stick Sandwich is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.stick_sandwich.cdlsticksandwich",
        "function": "compute_cdlsticksandwich",
        "output_columns": ["cdlsticksandwich"],
    },
    "cdltakuri": {
        "label": "探水竿Takuri",
        "formula": "Pattern(i,t) = 1 if Takuri is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.takuri.cdltakuri",
        "function": "compute_cdltakuri",
        "output_columns": ["cdltakuri"],
    },
    "cdltasukigap": {
        "label": "跳空并列阴阳线Tasuki Gap",
        "formula": "Pattern(i,t) = 1 for bullish Tasuki Gap, -1 for bearish Tasuki Gap, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.tasuki_gap.cdltasukigap",
        "function": "compute_cdltasukigap",
        "output_columns": ["cdltasukigap"],
    },
    "cdlthrusting": {
        "label": "插入形态Thrusting",
        "formula": "Pattern(i,t) = -1 if bearish Thrusting Pattern is detected on day t, else 0",
        "required_fields": ["open_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.thrusting_pattern.cdlthrusting",
        "function": "compute_cdlthrusting",
        "output_columns": ["cdlthrusting"],
    },
    "cdltristar": {
        "label": "三星形态Tristar",
        "formula": "Pattern(i,t) = 1 for bullish Tristar, -1 for bearish Tristar, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.tristar.cdltristar",
        "function": "compute_cdltristar",
        "output_columns": ["cdltristar"],
    },
    "cdlunique3river": {
        "label": "奇特三河床Unique 3 River",
        "formula": "Pattern(i,t) = 1 if bullish Unique 3 River is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.unique_three_river.cdlunique3river",
        "function": "compute_cdlunique3river",
        "output_columns": ["cdlunique3river"],
    },
    "cdlupsidegap2crows": {
        "label": "向上跳空两只乌鸦Upside Gap Two Crows",
        "formula": "Pattern(i,t) = -1 if bearish Upside Gap Two Crows is detected on day t, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.upside_gap_two_crows.cdlupsidegap2crows",
        "function": "compute_cdlupsidegap2crows",
        "output_columns": ["cdlupsidegap2crows"],
    },
    "cdlxsidegap3methods": {
        "label": "跳空并列三法XSide Gap 3 Methods",
        "formula": "Pattern(i,t) = 1 for bullish upside gap three methods, -1 for bearish downside gap three methods, else 0",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.domain.pattern_factor_formulas.xside_gap_three_methods.cdlxsidegap3methods",
        "function": "compute_cdlxsidegap3methods",
        "output_columns": ["cdlxsidegap3methods"],
    },
}
PATTERN_FACTOR_PARAMETERS: dict[str, dict[str, object]] = {
    "cdl2crows": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdl3blackcrows": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdl3inside": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdl3linestrike": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdl3starsinsouth": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdl3whitesoldiers": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlabandonedbaby": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdladvanceblock": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdlbelthold": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlbreakaway": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlclosingmarubozu": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlconcealbabyswallow": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlcounterattack": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdldarkcloudcover": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdldoji": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdldojistar": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdldragonflydoji": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlengulfing": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdleveningdojistar": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdleveningstar": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdlgapsidesidewhite": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlgravestonedoji": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdlhammer": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlhangingman": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdlharami": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlharamicross": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlhighwave": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlhikkake": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlhikkakemod": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlhomingpigeon": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlidentical3crows": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdlinneck": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdlinvertedhammer": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlkicking": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlkickingbylength": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlladderbottom": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdllongleggeddoji": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdllongline": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlmarubozu": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlmatchinglow": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlmathold": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlmorningdojistar": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlmorningstar": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlonneck": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdlpiercing": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlrickshawman": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlrisefall3methods": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlseparatinglines": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlshootingstar": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdlshortline": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlspinningtop": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlstalledpattern": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdlsticksandwich": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdltakuri": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdltasukigap": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlthrusting": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdltristar": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
    "cdlunique3river": {"signal_value": 1, "pattern_class": "kline_pattern"},
    "cdlupsidegap2crows": {"signal_value": -1, "pattern_class": "kline_pattern"},
    "cdlxsidegap3methods": {"signal_value": "up_or_down", "pattern_class": "kline_pattern"},
}


__all__ = [
    "DOMAIN_PATTERN_FORMULA_PREFIX",
    "LEGACY_PATTERN_FORMULA_PREFIX",
    "PATTERN_FACTOR_LIST",
    "PATTERN_FACTOR_PARAMETERS",
    "get_pattern_factor_category",
    "load_pattern_factor_function",
    "normalize_pattern_module_name",
]
