from __future__ import annotations

from importlib import import_module

def load_factor_function(module_name: str, function_name: str):
    module = import_module(module_name)
    func = getattr(module, function_name)
    return func


def get_factor_category(factor_name: str) -> str:
    """
    从因子 module 路径中解析分类目录。

    例：
    src.factor.assets.factors.factors.relative_strength_index.relative_strength_index_6
    -> relative_strength_index
    """
    module_name = FACTOR_LIST[factor_name]["module"]
    marker = ".factors.factors."
    if marker not in module_name:
        raise ValueError(f"无法从 module 路径解析因子分类: {module_name}")
    return module_name.split(marker, maxsplit=1)[1].split(".", maxsplit=1)[0]


FACTOR_LIST = {
    "accumulation_swing_index_26": {
        "label": "ASI振动升降指标",
        "formula": "ASI(i,t) = sum(SI(i,t-25), ..., SI(i,t))",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.factor.assets.factors.factors.accumulation_swing_index.accumulation_swing_index_26",
        "function": "compute_accumulation_swing_index_26",
        "output_columns": ["accumulation_swing_index_26"],
    },
    "accumulation_swing_index_average_26_10": {
        "label": "ASIT平滑振动升降指标",
        "formula": "ASIT(i,t) = mean(ASI(i,t-9), ..., ASI(i,t))",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.factor.assets.factors.factors.accumulation_swing_index.accumulation_swing_index_average_26_10",
        "function": "compute_accumulation_swing_index_average_26_10",
        "output_columns": ["accumulation_swing_index_average_26_10"]
    },
    "average_true_range_20": {
        "label": "真实波动20日平均值",
        "formula": "ATR(i,t) = mean(TR(i,t-19), ..., TR(i,t))",
        "required_fields": ["high_hfq", "low_hfq", "close_hfq"],
        "module": "src.factor.assets.factors.factors.average_true_range.average_true_range_20",
        "function": "compute_average_true_range_20",
        "output_columns": ["average_true_range_20"]
    },
    "bull_and_bear_index_3_6_12_21": {
        "label": "BBI多空指标",
        "formula": "BBI(i,t) = (MA3 + MA6 + MA12 + MA21) / 4",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.bull_and_bear_index.bull_and_bear_index_3_6_12_21",
        "function": "compute_bull_and_bear_index_3_6_12_21",
        "output_columns": ["bull_and_bear_index_3_6_12_21"]
    },
    "popularity_index_ar_26": {
        "label": "BRAR人气指标AR",
        "formula": "AR(i,t) = sum(H(i,t-k)-O(i,t-k), k=0..25) / sum(O(i,t-k)-L(i,t-k), k=0..25) * 100",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.factor.assets.factors.factors.popularity_willingness_index.popularity_index_ar_26",
        "function": "compute_popularity_index_ar_26",
        "output_columns": ["popularity_index_ar_26"],
    },
    "willingness_index_br_26": {
        "label": "BRAR意愿指标BR",
        "formula": "BR(i,t) = sum(max(0,H(i,t-k)-C(i,t-k-1)), k=0..25) / sum(max(0,C(i,t-k-1)-L(i,t-k)), k=0..25) * 100",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.factor.assets.factors.factors.popularity_willingness_index.willingness_index_br_26",
        "function": "compute_willingness_index_br_26",
        "output_columns": ["willingness_index_br_26"],
    },
    "bollinger_lower_band_20_2": {
        "label": "BOLL下轨",
        "formula": "BOLL_LOWER(i,t) = MA20(i,t) - 2 * STD20(i,t)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.bollinger_bands.bollinger_lower_band_20_2",
        "function": "compute_bollinger_lower_band_20_2",
        "output_columns": ["bollinger_lower_band_20_2"],
    },
    "bollinger_middle_band_20_2": {
        "label": "BOLL中轨",
        "formula": "BOLL_MID(i,t) = MA20(i,t)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.bollinger_bands.bollinger_middle_band_20_2",
        "function": "compute_bollinger_middle_band_20_2",
        "output_columns": ["bollinger_middle_band_20_2"],
    },
    "bollinger_upper_band_20_2": {
        "label": "BOLL上轨",
        "formula": "BOLL_UPPER(i,t) = MA20(i,t) + 2 * STD20(i,t)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.bollinger_bands.bollinger_upper_band_20_2",
        "function": "compute_bollinger_upper_band_20_2",
        "output_columns": ["bollinger_upper_band_20_2"],
    },
    "bias_ratio_6": {
        "label": "BIAS6乖离率",
        "formula": "BIAS6(i,t) = ((C(i,t) - MA6(i,t)) / MA6(i,t)) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.bias_ratio.bias_ratio_6",
        "function": "compute_bias_ratio_6",
        "output_columns": ["bias_ratio_6"],
    },
    "bias_ratio_12": {
        "label": "BIAS12乖离率",
        "formula": "BIAS12(i,t) = ((C(i,t) - MA12(i,t)) / MA12(i,t)) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.bias_ratio.bias_ratio_12",
        "function": "compute_bias_ratio_12",
        "output_columns": ["bias_ratio_12"],
    },
    "bias_ratio_24": {
        "label": "BIAS24乖离率",
        "formula": "BIAS24(i,t) = ((C(i,t) - MA24(i,t)) / MA24(i,t)) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.bias_ratio.bias_ratio_24",
        "function": "compute_bias_ratio_24",
        "output_columns": ["bias_ratio_24"],
    },
    "commodity_channel_index_14": {
        "label": "CCI顺势指标",
        "formula": "CCI(i,t) = (TP(i,t) - MA14(TP,i,t)) / (0.015 * MD14(TP,i,t))",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.commodity_channel_index.commodity_channel_index_14",
        "function": "compute_commodity_channel_index_14",
        "output_columns": ["commodity_channel_index_14"],
    },
    "price_momentum_index_20": {
        "label": "CR价格动量指标",
        "formula": "CR(i,t) = sum(max(0,H(i,t-k)-REF(MID,i,t-k,1)), k=0..19) / sum(max(0,REF(MID,i,t-k,1)-L(i,t-k)), k=0..19) * 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.price_momentum_index.price_momentum_index_20",
        "function": "compute_price_momentum_index_20",
        "output_columns": ["price_momentum_index_20"],
    },
    "parallel_line_difference_10_50": {
        "label": "DFMA平行线差指标DIF",
        "formula": "DFMA_DIF(i,t) = MA10(C,i,t) - MA50(C,i,t)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.parallel_line_difference.parallel_line_difference_10_50",
        "function": "compute_parallel_line_difference_10_50",
        "output_columns": ["parallel_line_difference_10_50"],
    },
    "parallel_line_difference_average_10_50_10": {
        "label": "DFMA平行线差指标DIFMA",
        "formula": "DFMA_DIFMA(i,t) = MA10(DFMA_DIF,i,t)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.parallel_line_difference.parallel_line_difference_average_10_50_10",
        "function": "compute_parallel_line_difference_average_10_50_10",
        "output_columns": ["parallel_line_difference_average_10_50_10"],
    },
    "consecutive_up_days": {
        "label": "连涨天数",
        "formula": "若 C(i,t) > C(i,t-1)，则 UPDAYS(i,t) = UPDAYS(i,t-1) + 1，否则为 0",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.consecutive_days.consecutive_up_days",
        "function": "compute_consecutive_up_days",
        "output_columns": ["consecutive_up_days"],
    },
    "consecutive_down_days": {
        "label": "连跌天数",
        "formula": "若 C(i,t) < C(i,t-1)，则 DOWNDAYS(i,t) = DOWNDAYS(i,t-1) + 1，否则为 0",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.consecutive_days.consecutive_down_days",
        "function": "compute_consecutive_down_days",
        "output_columns": ["consecutive_down_days"],
    },
    "directional_movement_positive_indicator_14": {
        "label": "DMI上升动向指标PDI",
        "formula": "DMI_PDI(i,t) = SUM(+DM,14) / SUM(TR,14) * 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.directional_movement_index.directional_movement_positive_indicator_14",
        "function": "compute_directional_movement_positive_indicator_14",
        "output_columns": ["directional_movement_positive_indicator_14"],
    },
    "directional_movement_negative_indicator_14": {
        "label": "DMI下降动向指标MDI",
        "formula": "DMI_MDI(i,t) = SUM(-DM,14) / SUM(TR,14) * 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.directional_movement_index.directional_movement_negative_indicator_14",
        "function": "compute_directional_movement_negative_indicator_14",
        "output_columns": ["directional_movement_negative_indicator_14"],
    },
    "average_directional_index_14_6": {
        "label": "DMI趋向平均指标ADX",
        "formula": "DMI_ADX(i,t) = MA6(DX(i,t))",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.directional_movement_index.average_directional_index_14_6",
        "function": "compute_average_directional_index_14_6",
        "output_columns": ["average_directional_index_14_6"],
    },
    "average_directional_index_rating_14_6": {
        "label": "DMI评估指标ADXR",
        "formula": "DMI_ADXR(i,t) = (ADX(i,t) + ADX(i,t-6)) / 2",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.directional_movement_index.average_directional_index_rating_14_6",
        "function": "compute_average_directional_index_rating_14_6",
        "output_columns": ["average_directional_index_rating_14_6"],
    },
    "exponential_moving_average_5": {
        "label": "指数移动平均EMA5",
        "formula": "EMA5(i,t) = alpha * C(i,t) + (1-alpha) * EMA5(i,t-1), alpha=2/6",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_5",
        "function": "compute_exponential_moving_average_5",
        "output_columns": ["exponential_moving_average_5"],
    },
    "exponential_moving_average_10": {
        "label": "指数移动平均EMA10",
        "formula": "EMA10(i,t) = alpha * C(i,t) + (1-alpha) * EMA10(i,t-1), alpha=2/11",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_10",
        "function": "compute_exponential_moving_average_10",
        "output_columns": ["exponential_moving_average_10"],
    },
    "exponential_moving_average_20": {
        "label": "指数移动平均EMA20",
        "formula": "EMA20(i,t) = alpha * C(i,t) + (1-alpha) * EMA20(i,t-1), alpha=2/21",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_20",
        "function": "compute_exponential_moving_average_20",
        "output_columns": ["exponential_moving_average_20"],
    },
    "exponential_moving_average_30": {
        "label": "指数移动平均EMA30",
        "formula": "EMA30(i,t) = alpha * C(i,t) + (1-alpha) * EMA30(i,t-1), alpha=2/31",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_30",
        "function": "compute_exponential_moving_average_30",
        "output_columns": ["exponential_moving_average_30"],
    },
    "exponential_moving_average_60": {
        "label": "指数移动平均EMA60",
        "formula": "EMA60(i,t) = alpha * C(i,t) + (1-alpha) * EMA60(i,t-1), alpha=2/61",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_60",
        "function": "compute_exponential_moving_average_60",
        "output_columns": ["exponential_moving_average_60"],
    },
    "exponential_moving_average_90": {
        "label": "指数移动平均EMA90",
        "formula": "EMA90(i,t) = alpha * C(i,t) + (1-alpha) * EMA90(i,t-1), alpha=2/91",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_90",
        "function": "compute_exponential_moving_average_90",
        "output_columns": ["exponential_moving_average_90"],
    },
    "exponential_moving_average_250": {
        "label": "指数移动平均EMA250",
        "formula": "EMA250(i,t) = alpha * C(i,t) + (1-alpha) * EMA250(i,t-1), alpha=2/251",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_250",
        "function": "compute_exponential_moving_average_250",
        "output_columns": ["exponential_moving_average_250"],
    },
    "ease_of_movement_value_14": {
        "label": "简易波动指标EMV",
        "formula": "EMV(i,t) = MA(MID(i,t) * (MA(VOL,14)/VOL) * (H-L) / MA(H-L,14), 14)",
        "required_fields": ["high_hfq", "low_hfq", "vol"],
        "module": "src.factor.assets.factors.factors.ease_of_movement_value.ease_of_movement_value_14",
        "function": "compute_ease_of_movement_value_14",
        "output_columns": ["ease_of_movement_value_14"],
    },
    "ease_of_movement_average_14_9": {
        "label": "简易波动指标MAEMV",
        "formula": "MAEMV(i,t) = MA(EMV(i,t), 9)",
        "required_fields": ["high_hfq", "low_hfq", "vol"],
        "module": "src.factor.assets.factors.factors.ease_of_movement_value.ease_of_movement_average_14_9",
        "function": "compute_ease_of_movement_average_14_9",
        "output_columns": ["ease_of_movement_average_14_9"],
    },
    "detrended_price_oscillator_20_10": {
        "label": "区间震荡线DPO",
        "formula": "DPO(i,t) = C(i,t) - REF(MA(C,i,t,20),10)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.detrended_price_oscillator.detrended_price_oscillator_20_10",
        "function": "compute_detrended_price_oscillator_20_10",
        "output_columns": ["detrended_price_oscillator_20_10"],
    },
    "detrended_price_oscillator_average_20_10_6": {
        "label": "区间震荡线MADPO",
        "formula": "MADPO(i,t) = MA(DPO(i,t),6)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.detrended_price_oscillator.detrended_price_oscillator_average_20_10_6",
        "function": "compute_detrended_price_oscillator_average_20_10_6",
        "output_columns": ["detrended_price_oscillator_average_20_10_6"],
    },
    "exponential_average_12": {
        "label": "指数平均数指标EXPMA12",
        "formula": "EXPMA12(i,t) = alpha * C(i,t) + (1-alpha) * EXPMA12(i,t-1), alpha=2/13",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.exponential_average.exponential_average_12",
        "function": "compute_exponential_average_12",
        "output_columns": ["exponential_average_12"],
    },
    "exponential_average_50": {
        "label": "指数平均数指标EXPMA50",
        "formula": "EXPMA50(i,t) = alpha * C(i,t) + (1-alpha) * EXPMA50(i,t-1), alpha=2/51",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.exponential_average.exponential_average_50",
        "function": "compute_exponential_average_50",
        "output_columns": ["exponential_average_50"],
    },
    "stochastic_j_line_9_3_3": {
        "label": "KDJ指标J线",
        "formula": "KDJ(i,t) = 3 * K(i,t) - 2 * D(i,t)",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.stochastic_oscillator.stochastic_j_line_9_3_3",
        "function": "compute_stochastic_j_line_9_3_3",
        "output_columns": ["stochastic_j_line_9_3_3"],
    },
    "stochastic_d_line_9_3_3": {
        "label": "KDJ指标D线",
        "formula": "D(i,t) = 2/3 * D(i,t-1) + 1/3 * K(i,t)",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.stochastic_oscillator.stochastic_d_line_9_3_3",
        "function": "compute_stochastic_d_line_9_3_3",
        "output_columns": ["stochastic_d_line_9_3_3"],
    },
    "stochastic_k_line_9_3_3": {
        "label": "KDJ指标K线",
        "formula": "K(i,t) = 2/3 * K(i,t-1) + 1/3 * RSV(i,t)",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.stochastic_oscillator.stochastic_k_line_9_3_3",
        "function": "compute_stochastic_k_line_9_3_3",
        "output_columns": ["stochastic_k_line_9_3_3"],
    },
    "keltner_channel_lower_band_20_10": {
        "label": "肯特纳交易通道下轨",
        "formula": "KTN_DOWN(i,t) = MA20(C,i,t) - 2 * ATR10(i,t)",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.keltner_channel.keltner_channel_lower_band_20_10",
        "function": "compute_keltner_channel_lower_band_20_10",
        "output_columns": ["keltner_channel_lower_band_20_10"],
    },
    "keltner_channel_middle_band_20_10": {
        "label": "肯特纳交易通道中轨",
        "formula": "KTN_MID(i,t) = MA20(C,i,t)",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.keltner_channel.keltner_channel_middle_band_20_10",
        "function": "compute_keltner_channel_middle_band_20_10",
        "output_columns": ["keltner_channel_middle_band_20_10"],
    },
    "keltner_channel_upper_band_20_10": {
        "label": "肯特纳交易通道上轨",
        "formula": "KTN_UPPER(i,t) = MA20(C,i,t) + 2 * ATR10(i,t)",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.keltner_channel.keltner_channel_upper_band_20_10",
        "function": "compute_keltner_channel_upper_band_20_10",
        "output_columns": ["keltner_channel_upper_band_20_10"],
    },
    "simple_moving_average_5": {
        "label": "简单移动平均MA5",
        "formula": "MA5(i,t) = mean(C(i,t-4), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_5",
        "function": "compute_simple_moving_average_5",
        "output_columns": ["simple_moving_average_5"],
    },
    "simple_moving_average_10": {
        "label": "简单移动平均MA10",
        "formula": "MA10(i,t) = mean(C(i,t-9), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_10",
        "function": "compute_simple_moving_average_10",
        "output_columns": ["simple_moving_average_10"],
    },
    "simple_moving_average_20": {
        "label": "简单移动平均MA20",
        "formula": "MA20(i,t) = mean(C(i,t-19), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_20",
        "function": "compute_simple_moving_average_20",
        "output_columns": ["simple_moving_average_20"],
    },
    "simple_moving_average_30": {
        "label": "简单移动平均MA30",
        "formula": "MA30(i,t) = mean(C(i,t-29), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_30",
        "function": "compute_simple_moving_average_30",
        "output_columns": ["simple_moving_average_30"],
    },
    "simple_moving_average_60": {
        "label": "简单移动平均MA60",
        "formula": "MA60(i,t) = mean(C(i,t-59), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_60",
        "function": "compute_simple_moving_average_60",
        "output_columns": ["simple_moving_average_60"],
    },
    "simple_moving_average_90": {
        "label": "简单移动平均MA90",
        "formula": "MA90(i,t) = mean(C(i,t-89), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_90",
        "function": "compute_simple_moving_average_90",
        "output_columns": ["simple_moving_average_90"],
    },
    "simple_moving_average_250": {
        "label": "简单移动平均MA250",
        "formula": "MA250(i,t) = mean(C(i,t-249), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_250",
        "function": "compute_simple_moving_average_250",
        "output_columns": ["simple_moving_average_250"],
    },
    "moving_average_convergence_divergence_histogram_12_26_9": {
        "label": "MACD柱线",
        "formula": "MACD(i,t) = 2 * (DIF(i,t) - DEA(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.moving_average_convergence_divergence.moving_average_convergence_divergence_histogram_12_26_9",
        "function": "compute_moving_average_convergence_divergence_histogram_12_26_9",
        "output_columns": ["moving_average_convergence_divergence_histogram_12_26_9"],
    },
    "moving_average_convergence_divergence_signal_line_12_26_9": {
        "label": "MACD DEA线",
        "formula": "DEA(i,t) = EMA(DIF(i,t), 9)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.moving_average_convergence_divergence.moving_average_convergence_divergence_signal_line_12_26_9",
        "function": "compute_moving_average_convergence_divergence_signal_line_12_26_9",
        "output_columns": ["moving_average_convergence_divergence_signal_line_12_26_9"],
    },
    "moving_average_convergence_divergence_difference_line_12_26_9": {
        "label": "MACD DIF线",
        "formula": "DIF(i,t) = EMA(C,i,t,12) - EMA(C,i,t,26)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.moving_average_convergence_divergence.moving_average_convergence_divergence_difference_line_12_26_9",
        "function": "compute_moving_average_convergence_divergence_difference_line_12_26_9",
        "output_columns": ["moving_average_convergence_divergence_difference_line_12_26_9"],
    },
    "mass_index_9_25": {
        "label": "梅斯线MASS",
        "formula": "MASS(i,t) = SUM(EMA(H-L,9) / EMA(EMA(H-L,9),9), 25)",
        "required_fields": ["high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.mass_index.mass_index_9_25",
        "function": "compute_mass_index_9_25",
        "output_columns": ["mass_index_9_25"],
    },
    "mass_index_average_9_25_6": {
        "label": "梅斯线平滑MA_MASS",
        "formula": "MA_MASS(i,t) = MA(MASS(i,t), 6)",
        "required_fields": ["high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.mass_index.mass_index_average_9_25_6",
        "function": "compute_mass_index_average_9_25_6",
        "output_columns": ["mass_index_average_9_25_6"],
    },
    "money_flow_index_14": {
        "label": "MFI资金流量指标",
        "formula": "MFI(i,t) = 100 - 100 / (1 + SUM(PMF,14) / SUM(NMF,14))",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq", "vol"],
        "module": "src.factor.assets.factors.factors.money_flow_index.money_flow_index_14",
        "function": "compute_money_flow_index_14",
        "output_columns": ["money_flow_index_14"],
    },
    "momentum_12": {
        "label": "动量指标MTM",
        "formula": "MTM(i,t) = C(i,t) - C(i,t-12)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.momentum.momentum_12",
        "function": "compute_momentum_12",
        "output_columns": ["momentum_12"],
    },
    "momentum_average_12_6": {
        "label": "动量指标平滑MTMMA",
        "formula": "MTMMA(i,t) = MA(MTM(i,t), 6)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.momentum.momentum_average_12_6",
        "function": "compute_momentum_average_12_6",
        "output_columns": ["momentum_average_12_6"],
    },
    "on_balance_volume": {
        "label": "能量潮指标OBV",
        "formula": "OBV(i,t) 按收盘涨跌方向对成交量进行累计加减",
        "required_fields": ["close_hfq", "vol"],
        "module": "src.factor.assets.factors.factors.on_balance_volume.on_balance_volume",
        "function": "compute_on_balance_volume",
        "output_columns": ["on_balance_volume"],
    },
    "psychological_line_12": {
        "label": "PSY心理线指标",
        "formula": "PSY(i,t) = COUNT(C(i,t) > C(i,t-1), 12) / 12 * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.psychological_line.psychological_line_12",
        "function": "compute_psychological_line_12",
        "output_columns": ["psychological_line_12"],
    },
    "psychological_line_average_12_6": {
        "label": "PSY心理线平滑指标",
        "formula": "PSYMA(i,t) = MA(PSY(i,t), 6)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.psychological_line.psychological_line_average_12_6",
        "function": "compute_psychological_line_average_12_6",
        "output_columns": ["psychological_line_average_12_6"],
    },
    "rate_of_change_12": {
        "label": "变动率指标ROC",
        "formula": "ROC(i,t) = (C(i,t) - C(i,t-12)) / C(i,t-12) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.rate_of_change.rate_of_change_12",
        "function": "compute_rate_of_change_12",
        "output_columns": ["rate_of_change_12"],
    },
    "rate_of_change_average_12_6": {
        "label": "变动率指标平滑MAROC",
        "formula": "MAROC(i,t) = MA(ROC(i,t), 6)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.rate_of_change.rate_of_change_average_12_6",
        "function": "compute_rate_of_change_average_12_6",
        "output_columns": ["rate_of_change_average_12_6"],
    },
    "relative_strength_index_6": {
        "label": "相对强弱指标RSI6",
        "formula": "RSI6(i,t) = SMA(MAX(C(i,t)-C(i,t-1),0),6,1) / SMA(ABS(C(i,t)-C(i,t-1)),6,1) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.relative_strength_index.relative_strength_index_6",
        "function": "compute_relative_strength_index_6",
        "output_columns": ["relative_strength_index_6"],
    },
    "relative_strength_index_12": {
        "label": "相对强弱指标RSI12",
        "formula": "RSI12(i,t) = SMA(MAX(C(i,t)-C(i,t-1),0),12,1) / SMA(ABS(C(i,t)-C(i,t-1)),12,1) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.relative_strength_index.relative_strength_index_12",
        "function": "compute_relative_strength_index_12",
        "output_columns": ["relative_strength_index_12"],
    },
    "relative_strength_index_24": {
        "label": "相对强弱指标RSI24",
        "formula": "RSI24(i,t) = SMA(MAX(C(i,t)-C(i,t-1),0),24,1) / SMA(ABS(C(i,t)-C(i,t-1)),24,1) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.relative_strength_index.relative_strength_index_24",
        "function": "compute_relative_strength_index_24",
        "output_columns": ["relative_strength_index_24"],
    },
    "donchian_channel_lower_band_20": {
        "label": "唐安奇通道下轨",
        "formula": "TAQ_DOWN(i,t) = LLV(L,20)",
        "required_fields": ["high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.donchian_channel.donchian_channel_lower_band_20",
        "function": "compute_donchian_channel_lower_band_20",
        "output_columns": ["donchian_channel_lower_band_20"],
    },
    "donchian_channel_middle_band_20": {
        "label": "唐安奇通道中轨",
        "formula": "TAQ_MID(i,t) = (TAQ_UP(i,t) + TAQ_DOWN(i,t)) / 2",
        "required_fields": ["high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.donchian_channel.donchian_channel_middle_band_20",
        "function": "compute_donchian_channel_middle_band_20",
        "output_columns": ["donchian_channel_middle_band_20"],
    },
    "donchian_channel_upper_band_20": {
        "label": "唐安奇通道上轨",
        "formula": "TAQ_UP(i,t) = HHV(H,20)",
        "required_fields": ["high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.donchian_channel.donchian_channel_upper_band_20",
        "function": "compute_donchian_channel_upper_band_20",
        "output_columns": ["donchian_channel_upper_band_20"],
    },
    "triple_exponential_oscillator_12": {
        "label": "三重指数平滑平均线TRIX",
        "formula": "TRIX(i,t) = (EMA3(i,t) - EMA3(i,t-1)) / EMA3(i,t-1) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.triple_exponential_oscillator.triple_exponential_oscillator_12",
        "function": "compute_triple_exponential_oscillator_12",
        "output_columns": ["triple_exponential_oscillator_12"],
    },
    "triple_exponential_oscillator_average_12_20": {
        "label": "三重指数平滑平均线TRMA",
        "formula": "TRMA(i,t) = MA(TRIX(i,t), 20)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.triple_exponential_oscillator.triple_exponential_oscillator_average_12_20",
        "function": "compute_triple_exponential_oscillator_average_12_20",
        "output_columns": ["triple_exponential_oscillator_average_12_20"],
    },
    "volume_ratio_26": {
        "label": "VR容量比率",
        "formula": "VR(i,t) = (SUM(AV,26) + 0.5 * SUM(CV,26)) / (SUM(BV,26) + 0.5 * SUM(CV,26)) * 100",
        "required_fields": ["close_hfq", "vol"],
        "module": "src.factor.assets.factors.factors.volume_ratio.volume_ratio_26",
        "function": "compute_volume_ratio_26",
        "output_columns": ["volume_ratio_26"],
    },
    "williams_percent_range_6": {
        "label": "W&R威廉指标6日",
        "formula": "WR6(i,t) = (HHV(H,6) - C(i,t)) / (HHV(H,6) - LLV(L,6)) * 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.williams_percent_range.williams_percent_range_6",
        "function": "compute_williams_percent_range_6",
        "output_columns": ["williams_percent_range_6"],
    },
    "williams_percent_range_10": {
        "label": "W&R威廉指标10日",
        "formula": "WR10(i,t) = (HHV(H,10) - C(i,t)) / (HHV(H,10) - LLV(L,10)) * 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.williams_percent_range.williams_percent_range_10",
        "function": "compute_williams_percent_range_10",
        "output_columns": ["williams_percent_range_10"],
    },
    "xue_si_channel_ii_line_1_102_7": {
        "label": "薛斯通道II 通道1",
        "formula": "XSII_TD1(i,t) = MA((2*C(i,t)+H(i,t)+L(i,t))/4, 5) * 102 / 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.xue_si_channel_ii.xue_si_channel_ii_line_1_102_7",
        "function": "compute_xue_si_channel_ii_line_1_102_7",
        "output_columns": ["xue_si_channel_ii_line_1_102_7"],
    },
    "xue_si_channel_ii_line_2_102_7": {
        "label": "薛斯通道II 通道2",
        "formula": "XSII_TD2(i,t) = MA((2*C(i,t)+H(i,t)+L(i,t))/4, 5) * 98 / 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.xue_si_channel_ii.xue_si_channel_ii_line_2_102_7",
        "function": "compute_xue_si_channel_ii_line_2_102_7",
        "output_columns": ["xue_si_channel_ii_line_2_102_7"],
    },
    "xue_si_channel_ii_line_3_102_7": {
        "label": "薛斯通道II 通道3",
        "formula": "XSII_TD3(i,t) = (1 + 7/100) * DMA(C(i,t), ABS((2*C(i,t)+H(i,t)+L(i,t))/4 - MA(C(i,t),20)) / MA(C(i,t),20))",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.xue_si_channel_ii.xue_si_channel_ii_line_3_102_7",
        "function": "compute_xue_si_channel_ii_line_3_102_7",
        "output_columns": ["xue_si_channel_ii_line_3_102_7"],
    },
    "xue_si_channel_ii_line_4_102_7": {
        "label": "薛斯通道II 通道4",
        "formula": "XSII_TD4(i,t) = (1 - 7/100) * DMA(C(i,t), ABS((2*C(i,t)+H(i,t)+L(i,t))/4 - MA(C(i,t),20)) / MA(C(i,t),20))",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.xue_si_channel_ii.xue_si_channel_ii_line_4_102_7",
        "function": "compute_xue_si_channel_ii_line_4_102_7",
        "output_columns": ["xue_si_channel_ii_line_4_102_7"],
    },
}
