from __future__ import annotations

from importlib import import_module

def load_factor_function(module_name: str, function_name: str):
    module = import_module(module_name)
    func = getattr(module, function_name)
    return func


FACTOR_LIST = {
    "asi_26": {
        "label": "ASI振动升降指标",
        "formula": "ASI(i,t) = sum(SI(i,t-25), ..., SI(i,t))",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.factor.assets.factors.factors.asi.asi_26",
        "function": "compute_asi_26",
        "output_columns": ["asi_26"],
    },
    "asit_26_10": {
        "label": "ASIT平滑振动升降指标",
        "formula": "ASIT(i,t) = mean(ASI(i,t-9), ..., ASI(i,t))",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.factor.assets.factors.factors.asi.asit_26_10",
        "function": "compute_asit_26_10",
        "output_columns": ["asit_26_10"]
    },
    "atr_20": {
        "label": "真实波动20日平均值",
        "formula": "ATR(i,t) = mean(TR(i,t-19), ..., TR(i,t))",
        "required_fields": ["high_hfq", "low_hfq", "close_hfq"],
        "module": "src.factor.assets.factors.factors.atr.atr_20",
        "function": "compute_atr_20",
        "output_columns": ["atr_20"]
    },
    "bbi_3_6_12_21": {
        "label": "BBI多空指标",
        "formula": "BBI(i,t) = (MA3 + MA6 + MA12 + MA21) / 4",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.bbi.bbi_3_6_12_21",
        "function": "compute_bbi_3_6_12_21",
        "output_columns": ["bbi_3_6_12_21"]
    },
    "brar_ar_26": {
        "label": "BRAR人气指标AR",
        "formula": "AR(i,t) = sum(H(i,t-k)-O(i,t-k), k=0..25) / sum(O(i,t-k)-L(i,t-k), k=0..25) * 100",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.factor.assets.factors.factors.brar.brar_ar_26",
        "function": "compute_brar_ar_26",
        "output_columns": ["brar_ar_26"],
    },
    "brar_br_26": {
        "label": "BRAR意愿指标BR",
        "formula": "BR(i,t) = sum(max(0,H(i,t-k)-C(i,t-k-1)), k=0..25) / sum(max(0,C(i,t-k-1)-L(i,t-k)), k=0..25) * 100",
        "required_fields": ["open_hfq", "high_hfq", "low_hfq", "close_hfq"],
        "module": "src.factor.assets.factors.factors.brar.brar_br_26",
        "function": "compute_brar_br_26",
        "output_columns": ["brar_br_26"],
    },
    "boll_lower_20_2": {
        "label": "BOLL下轨",
        "formula": "BOLL_LOWER(i,t) = MA20(i,t) - 2 * STD20(i,t)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.boll.boll_lower_20_2",
        "function": "compute_boll_lower_20_2",
        "output_columns": ["boll_lower_20_2"],
    },
    "boll_mid_20_2": {
        "label": "BOLL中轨",
        "formula": "BOLL_MID(i,t) = MA20(i,t)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.boll.boll_mid_20_2",
        "function": "compute_boll_mid_20_2",
        "output_columns": ["boll_mid_20_2"],
    },
    "boll_upper_20_2": {
        "label": "BOLL上轨",
        "formula": "BOLL_UPPER(i,t) = MA20(i,t) + 2 * STD20(i,t)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.boll.boll_upper_20_2",
        "function": "compute_boll_upper_20_2",
        "output_columns": ["boll_upper_20_2"],
    },
    "bias_6": {
        "label": "BIAS6乖离率",
        "formula": "BIAS6(i,t) = ((C(i,t) - MA6(i,t)) / MA6(i,t)) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.bias.bias_6",
        "function": "compute_bias_6",
        "output_columns": ["bias_6"],
    },
    "bias_12": {
        "label": "BIAS12乖离率",
        "formula": "BIAS12(i,t) = ((C(i,t) - MA12(i,t)) / MA12(i,t)) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.bias.bias_12",
        "function": "compute_bias_12",
        "output_columns": ["bias_12"],
    },
    "bias_24": {
        "label": "BIAS24乖离率",
        "formula": "BIAS24(i,t) = ((C(i,t) - MA24(i,t)) / MA24(i,t)) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.bias.bias_24",
        "function": "compute_bias_24",
        "output_columns": ["bias_24"],
    },
    "cci_14": {
        "label": "CCI顺势指标",
        "formula": "CCI(i,t) = (TP(i,t) - MA14(TP,i,t)) / (0.015 * MD14(TP,i,t))",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.cci.cci_14",
        "function": "compute_cci_14",
        "output_columns": ["cci_14"],
    },
    "cr_20": {
        "label": "CR价格动量指标",
        "formula": "CR(i,t) = sum(max(0,H(i,t-k)-REF(MID,i,t-k,1)), k=0..19) / sum(max(0,REF(MID,i,t-k,1)-L(i,t-k)), k=0..19) * 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.cr.cr_20",
        "function": "compute_cr_20",
        "output_columns": ["cr_20"],
    },
    "dfma_dif_10_50": {
        "label": "DFMA平行线差指标DIF",
        "formula": "DFMA_DIF(i,t) = MA10(C,i,t) - MA50(C,i,t)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.dfma.dfma_dif_10_50",
        "function": "compute_dfma_dif_10_50",
        "output_columns": ["dfma_dif_10_50"],
    },
    "dfma_difma_10_50_10": {
        "label": "DFMA平行线差指标DIFMA",
        "formula": "DFMA_DIFMA(i,t) = MA10(DFMA_DIF,i,t)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.dfma.dfma_difma_10_50_10",
        "function": "compute_dfma_difma_10_50_10",
        "output_columns": ["dfma_difma_10_50_10"],
    },
    "updays": {
        "label": "连涨天数",
        "formula": "若 C(i,t) > C(i,t-1)，则 UPDAYS(i,t) = UPDAYS(i,t-1) + 1，否则为 0",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.days.updays",
        "function": "compute_updays",
        "output_columns": ["updays"],
    },
    "downdays": {
        "label": "连跌天数",
        "formula": "若 C(i,t) < C(i,t-1)，则 DOWNDAYS(i,t) = DOWNDAYS(i,t-1) + 1，否则为 0",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.days.downdays",
        "function": "compute_downdays",
        "output_columns": ["downdays"],
    },
    "dmi_pdi_14": {
        "label": "DMI上升动向指标PDI",
        "formula": "DMI_PDI(i,t) = SUM(+DM,14) / SUM(TR,14) * 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.dmi.dmi_pdi_14",
        "function": "compute_dmi_pdi_14",
        "output_columns": ["dmi_pdi_14"],
    },
    "dmi_mdi_14": {
        "label": "DMI下降动向指标MDI",
        "formula": "DMI_MDI(i,t) = SUM(-DM,14) / SUM(TR,14) * 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.dmi.dmi_mdi_14",
        "function": "compute_dmi_mdi_14",
        "output_columns": ["dmi_mdi_14"],
    },
    "dmi_adx_14_6": {
        "label": "DMI趋向平均指标ADX",
        "formula": "DMI_ADX(i,t) = MA6(DX(i,t))",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.dmi.dmi_adx_14_6",
        "function": "compute_dmi_adx_14_6",
        "output_columns": ["dmi_adx_14_6"],
    },
    "dmi_adxr_14_6": {
        "label": "DMI评估指标ADXR",
        "formula": "DMI_ADXR(i,t) = (ADX(i,t) + ADX(i,t-6)) / 2",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.dmi.dmi_adxr_14_6",
        "function": "compute_dmi_adxr_14_6",
        "output_columns": ["dmi_adxr_14_6"],
    },
    "ema_5": {
        "label": "指数移动平均EMA5",
        "formula": "EMA5(i,t) = alpha * C(i,t) + (1-alpha) * EMA5(i,t-1), alpha=2/6",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ema.ema_5",
        "function": "compute_ema_5",
        "output_columns": ["ema_5"],
    },
    "ema_10": {
        "label": "指数移动平均EMA10",
        "formula": "EMA10(i,t) = alpha * C(i,t) + (1-alpha) * EMA10(i,t-1), alpha=2/11",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ema.ema_10",
        "function": "compute_ema_10",
        "output_columns": ["ema_10"],
    },
    "ema_20": {
        "label": "指数移动平均EMA20",
        "formula": "EMA20(i,t) = alpha * C(i,t) + (1-alpha) * EMA20(i,t-1), alpha=2/21",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ema.ema_20",
        "function": "compute_ema_20",
        "output_columns": ["ema_20"],
    },
    "ema_30": {
        "label": "指数移动平均EMA30",
        "formula": "EMA30(i,t) = alpha * C(i,t) + (1-alpha) * EMA30(i,t-1), alpha=2/31",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ema.ema_30",
        "function": "compute_ema_30",
        "output_columns": ["ema_30"],
    },
    "ema_60": {
        "label": "指数移动平均EMA60",
        "formula": "EMA60(i,t) = alpha * C(i,t) + (1-alpha) * EMA60(i,t-1), alpha=2/61",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ema.ema_60",
        "function": "compute_ema_60",
        "output_columns": ["ema_60"],
    },
    "ema_90": {
        "label": "指数移动平均EMA90",
        "formula": "EMA90(i,t) = alpha * C(i,t) + (1-alpha) * EMA90(i,t-1), alpha=2/91",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ema.ema_90",
        "function": "compute_ema_90",
        "output_columns": ["ema_90"],
    },
    "ema_250": {
        "label": "指数移动平均EMA250",
        "formula": "EMA250(i,t) = alpha * C(i,t) + (1-alpha) * EMA250(i,t-1), alpha=2/251",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ema.ema_250",
        "function": "compute_ema_250",
        "output_columns": ["ema_250"],
    },
    "emv_14": {
        "label": "简易波动指标EMV",
        "formula": "EMV(i,t) = MA(MID(i,t) * (MA(VOL,14)/VOL) * (H-L) / MA(H-L,14), 14)",
        "required_fields": ["high_hfq", "low_hfq", "vol"],
        "module": "src.factor.assets.factors.factors.emv.emv_14",
        "function": "compute_emv_14",
        "output_columns": ["emv_14"],
    },
    "maemv_14_9": {
        "label": "简易波动指标MAEMV",
        "formula": "MAEMV(i,t) = MA(EMV(i,t), 9)",
        "required_fields": ["high_hfq", "low_hfq", "vol"],
        "module": "src.factor.assets.factors.factors.emv.maemv_14_9",
        "function": "compute_maemv_14_9",
        "output_columns": ["maemv_14_9"],
    },
    "dpo_20_10": {
        "label": "区间震荡线DPO",
        "formula": "DPO(i,t) = C(i,t) - REF(MA(C,i,t,20),10)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.dpo.dpo_20_10",
        "function": "compute_dpo_20_10",
        "output_columns": ["dpo_20_10"],
    },
    "madpo_20_10_6": {
        "label": "区间震荡线MADPO",
        "formula": "MADPO(i,t) = MA(DPO(i,t),6)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.dpo.madpo_20_10_6",
        "function": "compute_madpo_20_10_6",
        "output_columns": ["madpo_20_10_6"],
    },
    "expma_12": {
        "label": "指数平均数指标EXPMA12",
        "formula": "EXPMA12(i,t) = alpha * C(i,t) + (1-alpha) * EXPMA12(i,t-1), alpha=2/13",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.expma.expma_12",
        "function": "compute_expma_12",
        "output_columns": ["expma_12"],
    },
    "expma_50": {
        "label": "指数平均数指标EXPMA50",
        "formula": "EXPMA50(i,t) = alpha * C(i,t) + (1-alpha) * EXPMA50(i,t-1), alpha=2/51",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.expma.expma_50",
        "function": "compute_expma_50",
        "output_columns": ["expma_50"],
    },
    "kdj_9_3_3": {
        "label": "KDJ指标J线",
        "formula": "KDJ(i,t) = 3 * K(i,t) - 2 * D(i,t)",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.kdj.kdj_9_3_3",
        "function": "compute_kdj_9_3_3",
        "output_columns": ["kdj_9_3_3"],
    },
    "kdj_d_9_3_3": {
        "label": "KDJ指标D线",
        "formula": "D(i,t) = 2/3 * D(i,t-1) + 1/3 * K(i,t)",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.kdj.kdj_d_9_3_3",
        "function": "compute_kdj_d_9_3_3",
        "output_columns": ["kdj_d_9_3_3"],
    },
    "kdj_k_9_3_3": {
        "label": "KDJ指标K线",
        "formula": "K(i,t) = 2/3 * K(i,t-1) + 1/3 * RSV(i,t)",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.kdj.kdj_k_9_3_3",
        "function": "compute_kdj_k_9_3_3",
        "output_columns": ["kdj_k_9_3_3"],
    },
    "ktn_down_20_10": {
        "label": "肯特纳交易通道下轨",
        "formula": "KTN_DOWN(i,t) = MA20(C,i,t) - 2 * ATR10(i,t)",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.ktn.ktn_down_20_10",
        "function": "compute_ktn_down_20_10",
        "output_columns": ["ktn_down_20_10"],
    },
    "ktn_mid_20_10": {
        "label": "肯特纳交易通道中轨",
        "formula": "KTN_MID(i,t) = MA20(C,i,t)",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.ktn.ktn_mid_20_10",
        "function": "compute_ktn_mid_20_10",
        "output_columns": ["ktn_mid_20_10"],
    },
    "ktn_upper_20_10": {
        "label": "肯特纳交易通道上轨",
        "formula": "KTN_UPPER(i,t) = MA20(C,i,t) + 2 * ATR10(i,t)",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.ktn.ktn_upper_20_10",
        "function": "compute_ktn_upper_20_10",
        "output_columns": ["ktn_upper_20_10"],
    },
    "ma_5": {
        "label": "简单移动平均MA5",
        "formula": "MA5(i,t) = mean(C(i,t-4), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ma.ma_5",
        "function": "compute_ma_5",
        "output_columns": ["ma_5"],
    },
    "ma_10": {
        "label": "简单移动平均MA10",
        "formula": "MA10(i,t) = mean(C(i,t-9), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ma.ma_10",
        "function": "compute_ma_10",
        "output_columns": ["ma_10"],
    },
    "ma_20": {
        "label": "简单移动平均MA20",
        "formula": "MA20(i,t) = mean(C(i,t-19), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ma.ma_20",
        "function": "compute_ma_20",
        "output_columns": ["ma_20"],
    },
    "ma_30": {
        "label": "简单移动平均MA30",
        "formula": "MA30(i,t) = mean(C(i,t-29), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ma.ma_30",
        "function": "compute_ma_30",
        "output_columns": ["ma_30"],
    },
    "ma_60": {
        "label": "简单移动平均MA60",
        "formula": "MA60(i,t) = mean(C(i,t-59), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ma.ma_60",
        "function": "compute_ma_60",
        "output_columns": ["ma_60"],
    },
    "ma_90": {
        "label": "简单移动平均MA90",
        "formula": "MA90(i,t) = mean(C(i,t-89), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ma.ma_90",
        "function": "compute_ma_90",
        "output_columns": ["ma_90"],
    },
    "ma_250": {
        "label": "简单移动平均MA250",
        "formula": "MA250(i,t) = mean(C(i,t-249), ..., C(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.ma.ma_250",
        "function": "compute_ma_250",
        "output_columns": ["ma_250"],
    },
    "macd_12_26_9": {
        "label": "MACD柱线",
        "formula": "MACD(i,t) = 2 * (DIF(i,t) - DEA(i,t))",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.macd.macd_12_26_9",
        "function": "compute_macd_12_26_9",
        "output_columns": ["macd_12_26_9"],
    },
    "macd_dea_12_26_9": {
        "label": "MACD DEA线",
        "formula": "DEA(i,t) = EMA(DIF(i,t), 9)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.macd.macd_dea_12_26_9",
        "function": "compute_macd_dea_12_26_9",
        "output_columns": ["macd_dea_12_26_9"],
    },
    "macd_dif_12_26_9": {
        "label": "MACD DIF线",
        "formula": "DIF(i,t) = EMA(C,i,t,12) - EMA(C,i,t,26)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.macd.macd_dif_12_26_9",
        "function": "compute_macd_dif_12_26_9",
        "output_columns": ["macd_dif_12_26_9"],
    },
    "mass_9_25": {
        "label": "梅斯线MASS",
        "formula": "MASS(i,t) = SUM(EMA(H-L,9) / EMA(EMA(H-L,9),9), 25)",
        "required_fields": ["high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.mass.mass_9_25",
        "function": "compute_mass_9_25",
        "output_columns": ["mass_9_25"],
    },
    "ma_mass_9_25_6": {
        "label": "梅斯线平滑MA_MASS",
        "formula": "MA_MASS(i,t) = MA(MASS(i,t), 6)",
        "required_fields": ["high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.mass.ma_mass_9_25_6",
        "function": "compute_ma_mass_9_25_6",
        "output_columns": ["ma_mass_9_25_6"],
    },
    "mfi_14": {
        "label": "MFI资金流量指标",
        "formula": "MFI(i,t) = 100 - 100 / (1 + SUM(PMF,14) / SUM(NMF,14))",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq", "vol"],
        "module": "src.factor.assets.factors.factors.mfi.mfi_14",
        "function": "compute_mfi_14",
        "output_columns": ["mfi_14"],
    },
    "mtm_12": {
        "label": "动量指标MTM",
        "formula": "MTM(i,t) = C(i,t) - C(i,t-12)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.mtm.mtm_12",
        "function": "compute_mtm_12",
        "output_columns": ["mtm_12"],
    },
    "mtmma_12_6": {
        "label": "动量指标平滑MTMMA",
        "formula": "MTMMA(i,t) = MA(MTM(i,t), 6)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.mtm.mtmma_12_6",
        "function": "compute_mtmma_12_6",
        "output_columns": ["mtmma_12_6"],
    },
    "obv": {
        "label": "能量潮指标OBV",
        "formula": "OBV(i,t) 按收盘涨跌方向对成交量进行累计加减",
        "required_fields": ["close_hfq", "vol"],
        "module": "src.factor.assets.factors.factors.obv.obv",
        "function": "compute_obv",
        "output_columns": ["obv"],
    },
    "psy_12": {
        "label": "PSY心理线指标",
        "formula": "PSY(i,t) = COUNT(C(i,t) > C(i,t-1), 12) / 12 * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.psy.psy_12",
        "function": "compute_psy_12",
        "output_columns": ["psy_12"],
    },
    "psyma_12_6": {
        "label": "PSY心理线平滑指标",
        "formula": "PSYMA(i,t) = MA(PSY(i,t), 6)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.psy.psyma_12_6",
        "function": "compute_psyma_12_6",
        "output_columns": ["psyma_12_6"],
    },
    "roc_12": {
        "label": "变动率指标ROC",
        "formula": "ROC(i,t) = (C(i,t) - C(i,t-12)) / C(i,t-12) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.roc.roc_12",
        "function": "compute_roc_12",
        "output_columns": ["roc_12"],
    },
    "maroc_12_6": {
        "label": "变动率指标平滑MAROC",
        "formula": "MAROC(i,t) = MA(ROC(i,t), 6)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.roc.maroc_12_6",
        "function": "compute_maroc_12_6",
        "output_columns": ["maroc_12_6"],
    },
    "rsi_6": {
        "label": "相对强弱指标RSI6",
        "formula": "RSI6(i,t) = SMA(MAX(C(i,t)-C(i,t-1),0),6,1) / SMA(ABS(C(i,t)-C(i,t-1)),6,1) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.rsi.rsi_6",
        "function": "compute_rsi_6",
        "output_columns": ["rsi_6"],
    },
    "rsi_12": {
        "label": "相对强弱指标RSI12",
        "formula": "RSI12(i,t) = SMA(MAX(C(i,t)-C(i,t-1),0),12,1) / SMA(ABS(C(i,t)-C(i,t-1)),12,1) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.rsi.rsi_12",
        "function": "compute_rsi_12",
        "output_columns": ["rsi_12"],
    },
    "rsi_24": {
        "label": "相对强弱指标RSI24",
        "formula": "RSI24(i,t) = SMA(MAX(C(i,t)-C(i,t-1),0),24,1) / SMA(ABS(C(i,t)-C(i,t-1)),24,1) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.rsi.rsi_24",
        "function": "compute_rsi_24",
        "output_columns": ["rsi_24"],
    },
    "taq_down_20": {
        "label": "唐安奇通道下轨",
        "formula": "TAQ_DOWN(i,t) = LLV(L,20)",
        "required_fields": ["high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.taq.taq_down_20",
        "function": "compute_taq_down_20",
        "output_columns": ["taq_down_20"],
    },
    "taq_mid_20": {
        "label": "唐安奇通道中轨",
        "formula": "TAQ_MID(i,t) = (TAQ_UP(i,t) + TAQ_DOWN(i,t)) / 2",
        "required_fields": ["high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.taq.taq_mid_20",
        "function": "compute_taq_mid_20",
        "output_columns": ["taq_mid_20"],
    },
    "taq_up_20": {
        "label": "唐安奇通道上轨",
        "formula": "TAQ_UP(i,t) = HHV(H,20)",
        "required_fields": ["high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.taq.taq_up_20",
        "function": "compute_taq_up_20",
        "output_columns": ["taq_up_20"],
    },
    "trix_12": {
        "label": "三重指数平滑平均线TRIX",
        "formula": "TRIX(i,t) = (EMA3(i,t) - EMA3(i,t-1)) / EMA3(i,t-1) * 100",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.trix.trix_12",
        "function": "compute_trix_12",
        "output_columns": ["trix_12"],
    },
    "trma_12_20": {
        "label": "三重指数平滑平均线TRMA",
        "formula": "TRMA(i,t) = MA(TRIX(i,t), 20)",
        "required_fields": ["close_hfq"],
        "module": "src.factor.assets.factors.factors.trix.trma_12_20",
        "function": "compute_trma_12_20",
        "output_columns": ["trma_12_20"],
    },
    "vr_26": {
        "label": "VR容量比率",
        "formula": "VR(i,t) = (SUM(AV,26) + 0.5 * SUM(CV,26)) / (SUM(BV,26) + 0.5 * SUM(CV,26)) * 100",
        "required_fields": ["close_hfq", "vol"],
        "module": "src.factor.assets.factors.factors.vr.vr_26",
        "function": "compute_vr_26",
        "output_columns": ["vr_26"],
    },
    "wr_6": {
        "label": "W&R威廉指标6日",
        "formula": "WR6(i,t) = (HHV(H,6) - C(i,t)) / (HHV(H,6) - LLV(L,6)) * 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.wr.wr_6",
        "function": "compute_wr_6",
        "output_columns": ["wr_6"],
    },
    "wr_10": {
        "label": "W&R威廉指标10日",
        "formula": "WR10(i,t) = (HHV(H,10) - C(i,t)) / (HHV(H,10) - LLV(L,10)) * 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.wr.wr_10",
        "function": "compute_wr_10",
        "output_columns": ["wr_10"],
    },
    "xsii_td1_102_7": {
        "label": "薛斯通道II 通道1",
        "formula": "XSII_TD1(i,t) = MA((2*C(i,t)+H(i,t)+L(i,t))/4, 5) * 102 / 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.xsii_td.xsii_td1_102_7",
        "function": "compute_xsii_td1_102_7",
        "output_columns": ["xsii_td1_102_7"],
    },
    "xsii_td2_102_7": {
        "label": "薛斯通道II 通道2",
        "formula": "XSII_TD2(i,t) = MA((2*C(i,t)+H(i,t)+L(i,t))/4, 5) * 98 / 100",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.xsii_td.xsii_td2_102_7",
        "function": "compute_xsii_td2_102_7",
        "output_columns": ["xsii_td2_102_7"],
    },
    "xsii_td3_102_7": {
        "label": "薛斯通道II 通道3",
        "formula": "XSII_TD3(i,t) = (1 + 7/100) * DMA(C(i,t), ABS((2*C(i,t)+H(i,t)+L(i,t))/4 - MA(C(i,t),20)) / MA(C(i,t),20))",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.xsii_td.xsii_td3_102_7",
        "function": "compute_xsii_td3_102_7",
        "output_columns": ["xsii_td3_102_7"],
    },
    "xsii_td4_102_7": {
        "label": "薛斯通道II 通道4",
        "formula": "XSII_TD4(i,t) = (1 - 7/100) * DMA(C(i,t), ABS((2*C(i,t)+H(i,t)+L(i,t))/4 - MA(C(i,t),20)) / MA(C(i,t),20))",
        "required_fields": ["close_hfq", "high_hfq", "low_hfq"],
        "module": "src.factor.assets.factors.factors.xsii_td.xsii_td4_102_7",
        "function": "compute_xsii_td4_102_7",
        "output_columns": ["xsii_td4_102_7"],
    },
}
