from __future__ import annotations

from importlib import import_module

def load_factor_function(module_name: str, function_name: str):
    module = import_module(module_name)
    func = getattr(module, function_name)
    return func


def get_factor_category(factor_name: str) -> str:
    """
    从因子 module 路径中解析分类目录。

    例：
    src.factor.assets.factors.factors.relative_strength_index.relative_strength_index_6
    -> relative_strength_index
    """
    module_name = FACTOR_LIST[factor_name]["module"]
    marker = ".factors.factors."
    if marker not in module_name:
        raise ValueError(f"无法从 module 路径解析因子分类: {module_name}")
    return module_name.split(marker, maxsplit=1)[1].split(".", maxsplit=1)[0]


FACTOR_LIST = {'accumulation_distribution_line': {'label': '累积派发线ADL',
                                    'formula': 'ADL(i,t) = cumulative_sum((((C(i,t) - L(i,t)) - (H(i,t) - C(i,t))) / '
                                               '(H(i,t) - L(i,t))) * VOL(i,t))',
                                    'required_fields': ['high_hfq', 'low_hfq', 'close_hfq', 'vol'],
                                    'module': 'src.factor.assets.factors.factors.accumulation_distribution_line.accumulation_distribution_line',
                                    'function': 'compute_accumulation_distribution_line',
                                    'output_columns': ['accumulation_distribution_line']},
 'accumulation_swing_index_26': {'label': 'ASI振动升降指标',
                                 'formula': 'ASI(i,t) = sum(SI(i,t-25), ..., SI(i,t))',
                                 'required_fields': ['open_hfq', 'high_hfq', 'low_hfq', 'close_hfq'],
                                 'module': 'src.factor.assets.factors.factors.accumulation_swing_index.accumulation_swing_index_26',
                                 'function': 'compute_accumulation_swing_index_26',
                                 'output_columns': ['accumulation_swing_index_26']},
 'accumulation_swing_index_average_26_10': {'label': 'ASIT平滑振动升降指标',
                                            'formula': 'ASIT(i,t) = mean(ASI(i,t-9), ..., ASI(i,t))',
                                            'required_fields': ['open_hfq', 'high_hfq', 'low_hfq', 'close_hfq'],
                                            'module': 'src.factor.assets.factors.factors.accumulation_swing_index.accumulation_swing_index_average_26_10',
                                            'function': 'compute_accumulation_swing_index_average_26_10',
                                            'output_columns': ['accumulation_swing_index_average_26_10']},
 'chaikin_accumulation_distribution_oscillator_3_10': {'label': '蔡金A/D振荡器ADOSC',
                                                       'formula': 'ADOSC(i,t) = EMA(ADL(i,t),3) - EMA(ADL(i,t),10)',
                                                       'required_fields': ['high_hfq',
                                                                           'low_hfq',
                                                                           'close_hfq',
                                                                           'vol'],
                                                       'module': 'src.factor.assets.factors.factors.chaikin_accumulation_distribution_oscillator.chaikin_accumulation_distribution_oscillator_3_10',
                                                       'function': 'compute_chaikin_accumulation_distribution_oscillator_3_10',
                                                       'output_columns': ['chaikin_accumulation_distribution_oscillator_3_10']},
 'annual_price_average_deviation_250': {'label': '一年均价偏离率',
                                        'formula': 'AnnualPriceAverageDeviation250(i,t) = C(i,t) / mean(C(i,t-249), '
                                                   '..., C(i,t)) - 1',
                                        'required_fields': ['close_hfq'],
                                        'module': 'src.factor.assets.factors.factors.annual_price_average_deviation.annual_price_average_deviation_250',
                                        'function': 'compute_annual_price_average_deviation_250',
                                        'output_columns': ['annual_price_average_deviation_250']},
 'annual_price_rank_position_250': {'label': '一年价格排序位置',
                                    'formula': 'AnnualPriceRankPosition250(i,t) = 1 + count(C(i,t-k) > C(i,t), '
                                               'k=0..249)',
                                    'required_fields': ['close_hfq'],
                                    'module': 'src.factor.assets.factors.factors.annual_price_rank_position.annual_price_rank_position_250',
                                    'function': 'compute_annual_price_rank_position_250',
                                    'output_columns': ['annual_price_rank_position_250']},
 'arron_down_25': {'label': 'Aroon指标下轨',
                   'formula': 'AroonDown(i,t) = ((25 - days_after_lowest_low(i,t)) / 25) * 100',
                   'required_fields': ['high_hfq', 'low_hfq'],
                   'module': 'src.factor.assets.factors.factors.arron_indicator.arron_down_25',
                   'function': 'compute_arron_down_25',
                   'output_columns': ['arron_down_25']},
 'arron_up_25': {'label': 'Aroon指标上轨',
                 'formula': 'AroonUp(i,t) = ((25 - days_after_highest_high(i,t)) / 25) * 100',
                 'required_fields': ['high_hfq', 'low_hfq'],
                 'module': 'src.factor.assets.factors.factors.arron_indicator.arron_up_25',
                 'function': 'compute_arron_up_25',
                 'output_columns': ['arron_up_25']},
 'arron_oscillator_25': {'label': 'Aroon振荡器',
                         'formula': 'AroonOscillator(i,t) = AroonUp(i,t) - AroonDown(i,t)',
                         'required_fields': ['high_hfq', 'low_hfq'],
                         'module': 'src.factor.assets.factors.factors.arron_indicator.arron_oscillator_25',
                         'function': 'compute_arron_oscillator_25',
                         'output_columns': ['arron_oscillator_25']},
 'average_directional_index_14_6': {'label': 'DMI趋向平均指标ADX',
                                    'formula': 'DMI_ADX(i,t) = MA6(DX(i,t))',
                                    'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                    'module': 'src.factor.assets.factors.factors.directional_movement_index.average_directional_index_14_6',
                                    'function': 'compute_average_directional_index_14_6',
                                    'output_columns': ['average_directional_index_14_6']},
 'average_directional_index_rating_14_6': {'label': 'DMI评估指标ADXR',
                                           'formula': 'DMI_ADXR(i,t) = (ADX(i,t) + ADX(i,t-6)) / 2',
                                           'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                           'module': 'src.factor.assets.factors.factors.directional_movement_index.average_directional_index_rating_14_6',
                                           'function': 'compute_average_directional_index_rating_14_6',
                                           'output_columns': ['average_directional_index_rating_14_6']},
 'average_price_hlc': {'label': '平均价格HLC',
                       'formula': 'AveragePriceHLC(i,t) = (H(i,t) + L(i,t) + C(i,t)) / 3',
                       'required_fields': ['high_hfq', 'low_hfq', 'close_hfq'],
                       'module': 'src.factor.assets.factors.factors.average_price.average_price_hlc',
                       'function': 'compute_average_price_hlc',
                       'output_columns': ['average_price_hlc']},
 'average_price_ohlc': {'label': '平均价格OHLC',
                        'formula': 'AveragePriceOHLC(i,t) = (O(i,t) + H(i,t) + L(i,t) + C(i,t)) / 4',
                        'required_fields': ['open_hfq', 'high_hfq', 'low_hfq', 'close_hfq'],
                        'module': 'src.factor.assets.factors.factors.average_price.average_price_ohlc',
                        'function': 'compute_average_price_ohlc',
                        'output_columns': ['average_price_ohlc']},
 'balance_of_power': {'label': '多空力量指标BOP',
                      'formula': 'BOP(i,t) = (C(i,t) - O(i,t)) / (H(i,t) - L(i,t))',
                      'required_fields': ['open_hfq', 'high_hfq', 'low_hfq', 'close_hfq'],
                      'module': 'src.factor.assets.factors.factors.balance_of_power.balance_of_power',
                      'function': 'compute_balance_of_power',
                      'output_columns': ['balance_of_power']},
 'average_true_range_14': {'label': '真实波动平均值',
                           'formula': 'ATR14(i,t) = mean(TR(i,t-13), ..., TR(i,t))',
                           'required_fields': ['high_hfq', 'low_hfq', 'close_hfq'],
                           'module': 'src.factor.assets.factors.factors.average_true_range.average_true_range_14',
                           'function': 'compute_average_true_range_14',
                           'output_columns': ['average_true_range_14']},
 'average_true_range_20': {'label': '真实波动平均值',
                           'formula': 'ATR(i,t) = mean(TR(i,t-19), ..., TR(i,t))',
                           'required_fields': ['high_hfq', 'low_hfq', 'close_hfq'],
                           'module': 'src.factor.assets.factors.factors.average_true_range.average_true_range_20',
                           'function': 'compute_average_true_range_20',
                           'output_columns': ['average_true_range_20']},
 'average_true_range_6': {'label': '真实波动平均值',
                          'formula': 'ATR6(i,t) = mean(TR(i,t-5), ..., TR(i,t))',
                          'required_fields': ['high_hfq', 'low_hfq', 'close_hfq'],
                          'module': 'src.factor.assets.factors.factors.average_true_range.average_true_range_6',
                          'function': 'compute_average_true_range_6',
                          'output_columns': ['average_true_range_6']},
 'average_turnover_rate_10': {'label': '平均换手率',
                              'formula': 'VOL10(i,t) = mean(turnover_rate(i,t-9), ..., turnover_rate(i,t))',
                              'required_fields': ['turnover_rate'],
                              'module': 'src.factor.assets.factors.factors.average_turnover_rate.average_turnover_rate_10',
                              'function': 'compute_average_turnover_rate_10',
                              'output_columns': ['average_turnover_rate_10']},
 'average_turnover_rate_120': {'label': '平均换手率',
                               'formula': 'VOL120(i,t) = mean(turnover_rate(i,t-119), ..., turnover_rate(i,t))',
                               'required_fields': ['turnover_rate'],
                               'module': 'src.factor.assets.factors.factors.average_turnover_rate.average_turnover_rate_120',
                               'function': 'compute_average_turnover_rate_120',
                               'output_columns': ['average_turnover_rate_120']},
 'average_turnover_rate_20': {'label': '平均换手率',
                              'formula': 'VOL20(i,t) = mean(turnover_rate(i,t-19), ..., turnover_rate(i,t))',
                              'required_fields': ['turnover_rate'],
                              'module': 'src.factor.assets.factors.factors.average_turnover_rate.average_turnover_rate_20',
                              'function': 'compute_average_turnover_rate_20',
                              'output_columns': ['average_turnover_rate_20']},
 'average_turnover_rate_240': {'label': '平均换手率',
                               'formula': 'VOL240(i,t) = mean(turnover_rate(i,t-239), ..., turnover_rate(i,t))',
                               'required_fields': ['turnover_rate'],
                               'module': 'src.factor.assets.factors.factors.average_turnover_rate.average_turnover_rate_240',
                               'function': 'compute_average_turnover_rate_240',
                               'output_columns': ['average_turnover_rate_240']},
 'average_turnover_rate_5': {'label': '平均换手率',
                             'formula': 'VOL5(i,t) = mean(turnover_rate(i,t-4), ..., turnover_rate(i,t))',
                             'required_fields': ['turnover_rate'],
                             'module': 'src.factor.assets.factors.factors.average_turnover_rate.average_turnover_rate_5',
                             'function': 'compute_average_turnover_rate_5',
                             'output_columns': ['average_turnover_rate_5']},
 'average_turnover_rate_60': {'label': '平均换手率',
                              'formula': 'VOL60(i,t) = mean(turnover_rate(i,t-59), ..., turnover_rate(i,t))',
                              'required_fields': ['turnover_rate'],
                              'module': 'src.factor.assets.factors.factors.average_turnover_rate.average_turnover_rate_60',
                              'function': 'compute_average_turnover_rate_60',
                              'output_columns': ['average_turnover_rate_60']},
 'bear_power_13': {'label': '空头力道BearPower',
                   'formula': 'BearPower(i,t) = (L(i,t) - EMA(C(i,t),13)) / C(i,t)',
                   'required_fields': ['low_hfq', 'close_hfq'],
                   'module': 'src.factor.assets.factors.factors.bull_power.bear_power_13',
                   'function': 'compute_bear_power_13',
                   'output_columns': ['bear_power_13']},
 'bias_ratio_12': {'label': 'BIAS乖离率',
                   'formula': 'BIAS12(i,t) = ((C(i,t) - MA12(i,t)) / MA12(i,t)) * 100',
                   'required_fields': ['close_hfq'],
                   'module': 'src.factor.assets.factors.factors.bias_ratio.bias_ratio_12',
                   'function': 'compute_bias_ratio_12',
                   'output_columns': ['bias_ratio_12']},
 'bias_ratio_24': {'label': 'BIAS乖离率',
                   'formula': 'BIAS24(i,t) = ((C(i,t) - MA24(i,t)) / MA24(i,t)) * 100',
                   'required_fields': ['close_hfq'],
                   'module': 'src.factor.assets.factors.factors.bias_ratio.bias_ratio_24',
                   'function': 'compute_bias_ratio_24',
                   'output_columns': ['bias_ratio_24']},
 'bias_ratio_6': {'label': 'BIAS乖离率',
                  'formula': 'BIAS6(i,t) = ((C(i,t) - MA6(i,t)) / MA6(i,t)) * 100',
                  'required_fields': ['close_hfq'],
                  'module': 'src.factor.assets.factors.factors.bias_ratio.bias_ratio_6',
                  'function': 'compute_bias_ratio_6',
                  'output_columns': ['bias_ratio_6']},
 'bias_ratio_60': {'label': 'BIAS乖离率',
                   'formula': 'BIAS60(i,t) = ((C(i,t) - MA60(i,t)) / MA60(i,t)) * 100',
                   'required_fields': ['close_hfq'],
                   'module': 'src.factor.assets.factors.factors.bias_ratio.bias_ratio_60',
                   'function': 'compute_bias_ratio_60',
                   'output_columns': ['bias_ratio_60']},
 'bollinger_lower_band_20_2': {'label': 'BOLL下轨',
                               'formula': 'BOLL_LOWER(i,t) = MA20(i,t) - 2 * STD20(i,t)',
                               'required_fields': ['close_hfq'],
                               'module': 'src.factor.assets.factors.factors.bollinger_bands.bollinger_lower_band_20_2',
                               'function': 'compute_bollinger_lower_band_20_2',
                               'output_columns': ['bollinger_lower_band_20_2']},
 'bollinger_middle_band_20_2': {'label': 'BOLL中轨',
                                'formula': 'BOLL_MID(i,t) = MA20(i,t)',
                                'required_fields': ['close_hfq'],
                                'module': 'src.factor.assets.factors.factors.bollinger_bands.bollinger_middle_band_20_2',
                                'function': 'compute_bollinger_middle_band_20_2',
                                'output_columns': ['bollinger_middle_band_20_2']},
 'bollinger_upper_band_20_2': {'label': 'BOLL上轨',
                               'formula': 'BOLL_UPPER(i,t) = MA20(i,t) + 2 * STD20(i,t)',
                               'required_fields': ['close_hfq'],
                               'module': 'src.factor.assets.factors.factors.bollinger_bands.bollinger_upper_band_20_2',
                               'function': 'compute_bollinger_upper_band_20_2',
                               'output_columns': ['bollinger_upper_band_20_2']},
 'bull_and_bear_index_3_6_12_21': {'label': 'BBI多空指标',
                                   'formula': 'BBI(i,t) = (MA3 + MA6 + MA12 + MA21) / 4',
                                   'required_fields': ['close_hfq'],
                                   'module': 'src.factor.assets.factors.factors.bull_and_bear_index.bull_and_bear_index_3_6_12_21',
                                   'function': 'compute_bull_and_bear_index_3_6_12_21',
                                   'output_columns': ['bull_and_bear_index_3_6_12_21']},
 'bull_and_bear_index_momentum_3_6_12_24': {'label': 'BBI动量BBIC',
                                            'formula': 'BBIC(i,t) = BBI(3,6,12,24)(i,t) / C(i,t)',
                                            'required_fields': ['close_hfq'],
                                            'module': 'src.factor.assets.factors.factors.bull_and_bear_index.bull_and_bear_index_momentum_3_6_12_24',
                                            'function': 'compute_bull_and_bear_index_momentum_3_6_12_24',
                                            'output_columns': ['bull_and_bear_index_momentum_3_6_12_24']},
 'bull_power_13': {'label': '多头力道BullPower',
                   'formula': 'BullPower(i,t) = (H(i,t) - EMA(C(i,t),13)) / C(i,t)',
                   'required_fields': ['high_hfq', 'close_hfq'],
                   'module': 'src.factor.assets.factors.factors.bull_power.bull_power_13',
                   'function': 'compute_bull_power_13',
                   'output_columns': ['bull_power_13']},
'chande_momentum_oscillator_14': {'label': '钱德动量摆动指标CMO',
                                   'formula': 'CMO14(i,t) = 100 * (SU(i,t,14) - SD(i,t,14)) / (SU(i,t,14) + SD(i,t,14))',
                                   'required_fields': ['close_hfq'],
                                   'module': 'src.factor.assets.factors.factors.chande_momentum_oscillator.chande_momentum_oscillator_14',
                                   'function': 'compute_chande_momentum_oscillator_14',
                                   'output_columns': ['chande_momentum_oscillator_14']},
'commodity_channel_index_10': {'label': 'CCI顺势指标',
                                'formula': 'CCI10(i,t) = (TYP(i,t) - MA10(TYP,i,t)) / (0.015 * AVEDEV10(TYP,i,t))',
                                'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                'module': 'src.factor.assets.factors.factors.commodity_channel_index.commodity_channel_index_10',
                                'function': 'compute_commodity_channel_index_10',
                                'output_columns': ['commodity_channel_index_10']},
 'commodity_channel_index_120': {'label': 'CCI顺势指标',
                                 'formula': 'CCI120(i,t) = (TYP(i,t) - MA120(TYP,i,t)) / (0.015 * AVEDEV120(TYP,i,t))',
                                 'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                 'module': 'src.factor.assets.factors.factors.commodity_channel_index.commodity_channel_index_120',
                                 'function': 'compute_commodity_channel_index_120',
                                 'output_columns': ['commodity_channel_index_120']},
 'commodity_channel_index_14': {'label': 'CCI顺势指标',
                                'formula': 'CCI(i,t) = (TP(i,t) - MA14(TP,i,t)) / (0.015 * MD14(TP,i,t))',
                                'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                'module': 'src.factor.assets.factors.factors.commodity_channel_index.commodity_channel_index_14',
                                'function': 'compute_commodity_channel_index_14',
                                'output_columns': ['commodity_channel_index_14']},
 'commodity_channel_index_20': {'label': 'CCI顺势指标',
                                'formula': 'CCI20(i,t) = (TYP(i,t) - MA20(TYP,i,t)) / (0.015 * AVEDEV20(TYP,i,t))',
                                'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                'module': 'src.factor.assets.factors.factors.commodity_channel_index.commodity_channel_index_20',
                                'function': 'compute_commodity_channel_index_20',
                                'output_columns': ['commodity_channel_index_20']},
 'commodity_channel_index_60': {'label': 'CCI顺势指标',
                                'formula': 'CCI60(i,t) = (TYP(i,t) - MA60(TYP,i,t)) / (0.015 * AVEDEV60(TYP,i,t))',
                                'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                'module': 'src.factor.assets.factors.factors.commodity_channel_index.commodity_channel_index_60',
                                'function': 'compute_commodity_channel_index_60',
                                'output_columns': ['commodity_channel_index_60']},
 'consecutive_down_days': {'label': '连跌天数',
                           'formula': '若 C(i,t) < C(i,t-1)，则 DOWNDAYS(i,t) = DOWNDAYS(i,t-1) + 1，否则为 0',
                           'required_fields': ['close_hfq'],
                           'module': 'src.factor.assets.factors.factors.consecutive_days.consecutive_down_days',
                           'function': 'compute_consecutive_down_days',
                           'output_columns': ['consecutive_down_days']},
 'consecutive_up_days': {'label': '连涨天数',
                         'formula': '若 C(i,t) > C(i,t-1)，则 UPDAYS(i,t) = UPDAYS(i,t-1) + 1，否则为 0',
                         'required_fields': ['close_hfq'],
                         'module': 'src.factor.assets.factors.factors.consecutive_days.consecutive_up_days',
                         'function': 'compute_consecutive_up_days',
                         'output_columns': ['consecutive_up_days']},
 'detrended_price_oscillator_20_10': {'label': '区间震荡线DPO',
                                      'formula': 'DPO(i,t) = C(i,t) - REF(MA(C,i,t,20),10)',
                                      'required_fields': ['close_hfq'],
                                      'module': 'src.factor.assets.factors.factors.detrended_price_oscillator.detrended_price_oscillator_20_10',
                                      'function': 'compute_detrended_price_oscillator_20_10',
                                      'output_columns': ['detrended_price_oscillator_20_10']},
 'detrended_price_oscillator_average_20_10_6': {'label': '区间震荡线MADPO',
                                                'formula': 'MADPO(i,t) = MA(DPO(i,t),6)',
                                                'required_fields': ['close_hfq'],
                                                'module': 'src.factor.assets.factors.factors.detrended_price_oscillator.detrended_price_oscillator_average_20_10_6',
                                                'function': 'compute_detrended_price_oscillator_average_20_10_6',
                                                'output_columns': ['detrended_price_oscillator_average_20_10_6']},
 'directional_movement_negative_indicator_14': {'label': 'DMI下降动向指标MDI',
                                                'formula': 'DMI_MDI(i,t) = SUM(-DM,14) / SUM(TR,14) * 100',
                                                'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                                'module': 'src.factor.assets.factors.factors.directional_movement_index.directional_movement_negative_indicator_14',
                                                'function': 'compute_directional_movement_negative_indicator_14',
                                                'output_columns': ['directional_movement_negative_indicator_14']},
 'directional_movement_positive_indicator_14': {'label': 'DMI上升动向指标PDI',
                                                'formula': 'DMI_PDI(i,t) = SUM(+DM,14) / SUM(TR,14) * 100',
                                                'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                                'module': 'src.factor.assets.factors.factors.directional_movement_index.directional_movement_positive_indicator_14',
                                                'function': 'compute_directional_movement_positive_indicator_14',
                                                'output_columns': ['directional_movement_positive_indicator_14']},
 'directional_movement_index_14': {'label': '动向指数DX',
                                   'formula': 'DX14(i,t) = |PDI14(i,t) - MDI14(i,t)| / (PDI14(i,t) + MDI14(i,t)) * 100',
                                   'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                   'module': 'src.factor.assets.factors.factors.directional_movement_index.directional_movement_index_14',
                                   'function': 'compute_directional_movement_index_14',
                                   'output_columns': ['directional_movement_index_14']},
 'double_exponential_moving_average_10': {'label': '双指数移动平均DEMA',
                                           'formula': 'DEMA10(i,t) = 2 * EMA10(i,t) - EMA(EMA10(i,t),10)',
                                           'required_fields': ['close_hfq'],
                                           'module': 'src.factor.assets.factors.factors.double_exponential_moving_average.double_exponential_moving_average_10',
                                           'function': 'compute_double_exponential_moving_average_10',
                                           'output_columns': ['double_exponential_moving_average_10']},
 'double_exponential_moving_average_20': {'label': '双指数移动平均DEMA',
                                           'formula': 'DEMA20(i,t) = 2 * EMA20(i,t) - EMA(EMA20(i,t),20)',
                                           'required_fields': ['close_hfq'],
                                           'module': 'src.factor.assets.factors.factors.double_exponential_moving_average.double_exponential_moving_average_20',
                                           'function': 'compute_double_exponential_moving_average_20',
                                           'output_columns': ['double_exponential_moving_average_20']},
 'double_exponential_moving_average_60': {'label': '双指数移动平均DEMA',
                                           'formula': 'DEMA60(i,t) = 2 * EMA60(i,t) - EMA(EMA60(i,t),60)',
                                           'required_fields': ['close_hfq'],
                                           'module': 'src.factor.assets.factors.factors.double_exponential_moving_average.double_exponential_moving_average_60',
                                           'function': 'compute_double_exponential_moving_average_60',
                                           'output_columns': ['double_exponential_moving_average_60']},
 'donchian_channel_lower_band_20': {'label': '唐安奇通道下轨',
                                    'formula': 'TAQ_DOWN(i,t) = LLV(L,20)',
                                    'required_fields': ['high_hfq', 'low_hfq'],
                                    'module': 'src.factor.assets.factors.factors.donchian_channel.donchian_channel_lower_band_20',
                                    'function': 'compute_donchian_channel_lower_band_20',
                                    'output_columns': ['donchian_channel_lower_band_20']},
 'donchian_channel_middle_band_20': {'label': '唐安奇通道中轨',
                                     'formula': 'TAQ_MID(i,t) = (TAQ_UP(i,t) + TAQ_DOWN(i,t)) / 2',
                                     'required_fields': ['high_hfq', 'low_hfq'],
                                     'module': 'src.factor.assets.factors.factors.donchian_channel.donchian_channel_middle_band_20',
                                     'function': 'compute_donchian_channel_middle_band_20',
                                     'output_columns': ['donchian_channel_middle_band_20']},
 'donchian_channel_upper_band_20': {'label': '唐安奇通道上轨',
                                    'formula': 'TAQ_UP(i,t) = HHV(H,20)',
                                    'required_fields': ['high_hfq', 'low_hfq'],
                                    'module': 'src.factor.assets.factors.factors.donchian_channel.donchian_channel_upper_band_20',
                                    'function': 'compute_donchian_channel_upper_band_20',
                                    'output_columns': ['donchian_channel_upper_band_20']},
 'ease_of_movement_average_14_9': {'label': '简易波动指标MAEMV',
                                   'formula': 'MAEMV(i,t) = MA(EMV(i,t), 9)',
                                   'required_fields': ['high_hfq', 'low_hfq', 'vol'],
                                   'module': 'src.factor.assets.factors.factors.ease_of_movement_value.ease_of_movement_average_14_9',
                                   'function': 'compute_ease_of_movement_average_14_9',
                                   'output_columns': ['ease_of_movement_average_14_9']},
 'ease_of_movement_value_14': {'label': '简易波动指标EMV',
                               'formula': 'EMV(i,t) = MA(MID(i,t) * (MA(VOL,14)/VOL) * (H-L) / MA(H-L,14), 14)',
                               'required_fields': ['high_hfq', 'low_hfq', 'vol'],
                               'module': 'src.factor.assets.factors.factors.ease_of_movement_value.ease_of_movement_value_14',
                               'function': 'compute_ease_of_movement_value_14',
                               'output_columns': ['ease_of_movement_value_14']},
 'exponential_average_12': {'label': '指数平均数指标EXPMA',
                            'formula': 'EXPMA12(i,t) = alpha * C(i,t) + (1-alpha) * EXPMA12(i,t-1), alpha=2/13',
                            'required_fields': ['close_hfq'],
                            'module': 'src.factor.assets.factors.factors.exponential_average.exponential_average_12',
                            'function': 'compute_exponential_average_12',
                            'output_columns': ['exponential_average_12']},
 'exponential_average_50': {'label': '指数平均数指标EXPMA',
                            'formula': 'EXPMA50(i,t) = alpha * C(i,t) + (1-alpha) * EXPMA50(i,t-1), alpha=2/51',
                            'required_fields': ['close_hfq'],
                            'module': 'src.factor.assets.factors.factors.exponential_average.exponential_average_50',
                            'function': 'compute_exponential_average_50',
                            'output_columns': ['exponential_average_50']},
 'exponential_moving_average_10': {'label': '指数移动平均EMA',
                                   'formula': 'EMA10(i,t) = alpha * C(i,t) + (1-alpha) * EMA10(i,t-1), alpha=2/11',
                                   'required_fields': ['close_hfq'],
                                   'module': 'src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_10',
                                   'function': 'compute_exponential_moving_average_10',
                                   'output_columns': ['exponential_moving_average_10']},
 'exponential_moving_average_20': {'label': '指数移动平均EMA',
                                   'formula': 'EMA20(i,t) = alpha * C(i,t) + (1-alpha) * EMA20(i,t-1), alpha=2/21',
                                   'required_fields': ['close_hfq'],
                                   'module': 'src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_20',
                                   'function': 'compute_exponential_moving_average_20',
                                   'output_columns': ['exponential_moving_average_20']},
 'exponential_moving_average_250': {'label': '指数移动平均EMA',
                                    'formula': 'EMA250(i,t) = alpha * C(i,t) + (1-alpha) * EMA250(i,t-1), alpha=2/251',
                                    'required_fields': ['close_hfq'],
                                    'module': 'src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_250',
                                    'function': 'compute_exponential_moving_average_250',
                                    'output_columns': ['exponential_moving_average_250']},
 'exponential_moving_average_30': {'label': '指数移动平均EMA',
                                   'formula': 'EMA30(i,t) = alpha * C(i,t) + (1-alpha) * EMA30(i,t-1), alpha=2/31',
                                   'required_fields': ['close_hfq'],
                                   'module': 'src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_30',
                                   'function': 'compute_exponential_moving_average_30',
                                   'output_columns': ['exponential_moving_average_30']},
 'exponential_moving_average_5': {'label': '指数移动平均EMA',
                                  'formula': 'EMA5(i,t) = alpha * C(i,t) + (1-alpha) * EMA5(i,t-1), alpha=2/6',
                                  'required_fields': ['close_hfq'],
                                  'module': 'src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_5',
                                  'function': 'compute_exponential_moving_average_5',
                                  'output_columns': ['exponential_moving_average_5']},
 'exponential_moving_average_60': {'label': '指数移动平均EMA',
                                   'formula': 'EMA60(i,t) = alpha * C(i,t) + (1-alpha) * EMA60(i,t-1), alpha=2/61',
                                   'required_fields': ['close_hfq'],
                                   'module': 'src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_60',
                                   'function': 'compute_exponential_moving_average_60',
                                   'output_columns': ['exponential_moving_average_60']},
 'exponential_moving_average_90': {'label': '指数移动平均EMA',
                                   'formula': 'EMA90(i,t) = alpha * C(i,t) + (1-alpha) * EMA90(i,t-1), alpha=2/91',
                                   'required_fields': ['close_hfq'],
                                   'module': 'src.factor.assets.factors.factors.exponential_moving_average.exponential_moving_average_90',
                                   'function': 'compute_exponential_moving_average_90',
                                   'output_columns': ['exponential_moving_average_90']},
 'keltner_channel_lower_band_20_10': {'label': '肯特纳交易通道下轨',
                                      'formula': 'KTN_DOWN(i,t) = MA20(C,i,t) - 2 * ATR10(i,t)',
                                      'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                      'module': 'src.factor.assets.factors.factors.keltner_channel.keltner_channel_lower_band_20_10',
                                      'function': 'compute_keltner_channel_lower_band_20_10',
                                      'output_columns': ['keltner_channel_lower_band_20_10']},
 'keltner_channel_middle_band_20_10': {'label': '肯特纳交易通道中轨',
                                       'formula': 'KTN_MID(i,t) = MA20(C,i,t)',
                                       'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                       'module': 'src.factor.assets.factors.factors.keltner_channel.keltner_channel_middle_band_20_10',
                                       'function': 'compute_keltner_channel_middle_band_20_10',
                                       'output_columns': ['keltner_channel_middle_band_20_10']},
 'keltner_channel_upper_band_20_10': {'label': '肯特纳交易通道上轨',
                                      'formula': 'KTN_UPPER(i,t) = MA20(C,i,t) + 2 * ATR10(i,t)',
                                      'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                      'module': 'src.factor.assets.factors.factors.keltner_channel.keltner_channel_upper_band_20_10',
                                      'function': 'compute_keltner_channel_upper_band_20_10',
                                      'output_columns': ['keltner_channel_upper_band_20_10']},
 'kaufman_adaptive_moving_average_10_2_30': {'label': '考夫曼自适应均线KAMA',
                                             'formula': 'KAMA(10,2,30)(i,t) = adaptive moving average of C(i,t) with ER window 10, fast=2, slow=30',
                                             'required_fields': ['close_hfq'],
                                             'module': 'src.factor.assets.factors.factors.kaufman_adaptive_moving_average.kaufman_adaptive_moving_average_10_2_30',
                                             'function': 'compute_kaufman_adaptive_moving_average_10_2_30',
                                             'output_columns': ['kaufman_adaptive_moving_average_10_2_30']},
 'mass_index_9_25': {'label': '梅斯线MASS',
                     'formula': 'MASS(i,t) = SUM(EMA(H-L,9) / EMA(EMA(H-L,9),9), 25)',
                     'required_fields': ['high_hfq', 'low_hfq'],
                     'module': 'src.factor.assets.factors.factors.mass_index.mass_index_9_25',
                     'function': 'compute_mass_index_9_25',
                     'output_columns': ['mass_index_9_25']},
 'mass_index_average_9_25_6': {'label': '梅斯线平滑MA_MASS',
                               'formula': 'MA_MASS(i,t) = MA(MASS(i,t), 6)',
                               'required_fields': ['high_hfq', 'low_hfq'],
                               'module': 'src.factor.assets.factors.factors.mass_index.mass_index_average_9_25_6',
                               'function': 'compute_mass_index_average_9_25_6',
                               'output_columns': ['mass_index_average_9_25_6']},
 'momentum_12': {'label': '动量指标MTM',
                 'formula': 'MTM(i,t) = C(i,t) - C(i,t-12)',
                 'required_fields': ['close_hfq'],
                 'module': 'src.factor.assets.factors.factors.momentum.momentum_12',
                 'function': 'compute_momentum_12',
                 'output_columns': ['momentum_12']},
 'momentum_average_12_6': {'label': '动量指标平滑MTMMA',
                           'formula': 'MTMMA(i,t) = MA(MTM(i,t), 6)',
                           'required_fields': ['close_hfq'],
                           'module': 'src.factor.assets.factors.factors.momentum.momentum_average_12_6',
                           'function': 'compute_momentum_average_12_6',
                           'output_columns': ['momentum_average_12_6']},
 'minus_directional_movement_14': {'label': '负向动向值MINUS_DM',
                                   'formula': 'MINUS_DM14(i,t) = SUM(minus_dm(i,t), 14)',
                                   'required_fields': ['high_hfq', 'low_hfq'],
                                   'module': 'src.factor.assets.factors.factors.directional_movement_index.minus_directional_movement_14',
                                   'function': 'compute_minus_directional_movement_14',
                                   'output_columns': ['minus_directional_movement_14']},
 'plus_directional_movement_14': {'label': '正向动向值PLUS_DM',
                                  'formula': 'PLUS_DM14(i,t) = SUM(plus_dm(i,t), 14)',
                                  'required_fields': ['high_hfq', 'low_hfq'],
                                  'module': 'src.factor.assets.factors.factors.directional_movement_index.plus_directional_movement_14',
                                  'function': 'compute_plus_directional_movement_14',
                                  'output_columns': ['plus_directional_movement_14']},
 'money_flow_20': {'label': '资金流量',
                   'formula': 'MoneyFlow20(i,t) = sum(((C+H+L)/3*VOL)(i,t-k), k=0..19)',
                   'required_fields': ['close_hfq', 'high_hfq', 'low_hfq', 'vol'],
                   'module': 'src.factor.assets.factors.factors.money_flow.money_flow_20',
                   'function': 'compute_money_flow_20',
                   'output_columns': ['money_flow_20']},
 'money_flow_index_14': {'label': 'MFI资金流量指标',
                         'formula': 'MFI(i,t) = 100 - 100 / (1 + SUM(PMF,14) / SUM(NMF,14))',
                         'required_fields': ['close_hfq', 'high_hfq', 'low_hfq', 'vol'],
                         'module': 'src.factor.assets.factors.factors.money_flow_index.money_flow_index_14',
                         'function': 'compute_money_flow_index_14',
                         'output_columns': ['money_flow_index_14']},
 'monthly_price_average_deviation_20': {'label': '一月均价偏离率',
                                        'formula': 'MonthlyPriceAverageDeviation20(i,t) = C(i,t) / mean(C(i,t-19), '
                                                   '..., C(i,t)) - 1',
                                        'required_fields': ['close_hfq'],
                                        'module': 'src.factor.assets.factors.factors.monthly_price_average_deviation.monthly_price_average_deviation_20',
                                        'function': 'compute_monthly_price_average_deviation_20',
                                        'output_columns': ['monthly_price_average_deviation_20']},
 'monthly_return_rank_score_20': {'label': '一月收益排名得分',
                                  'formula': 'MonthlyReturnRankScore20(i,t) = 1 - rank_desc(R20(i,t)) / '
                                             'count(R20(i,t)), R20=C(i,t)/C(i,t-20)-1',
                                  'required_fields': ['close_hfq'],
                                  'module': 'src.factor.assets.factors.factors.monthly_return_rank_score.monthly_return_rank_score_20',
                                  'function': 'compute_monthly_return_rank_score_20',
                                  'output_columns': ['monthly_return_rank_score_20']},
 'moving_average_convergence_divergence_difference_line_12_26_9': {'label': 'MACD DIF线',
                                                                   'formula': 'DIF(i,t) = EMA(C,i,t,12) - '
                                                                              'EMA(C,i,t,26)',
                                                                   'required_fields': ['close_hfq'],
                                                                   'module': 'src.factor.assets.factors.factors.moving_average_convergence_divergence.moving_average_convergence_divergence_difference_line_12_26_9',
                                                                   'function': 'compute_moving_average_convergence_divergence_difference_line_12_26_9',
                                                                   'output_columns': ['moving_average_convergence_divergence_difference_line_12_26_9']},
 'moving_average_convergence_divergence_histogram_12_26_9': {'label': 'MACD柱线',
                                                             'formula': 'MACD(i,t) = 2 * (DIF(i,t) - DEA(i,t))',
                                                             'required_fields': ['close_hfq'],
                                                             'module': 'src.factor.assets.factors.factors.moving_average_convergence_divergence.moving_average_convergence_divergence_histogram_12_26_9',
                                                             'function': 'compute_moving_average_convergence_divergence_histogram_12_26_9',
                                                             'output_columns': ['moving_average_convergence_divergence_histogram_12_26_9']},
 'moving_average_convergence_divergence_signal_line_12_26_9': {'label': 'MACD DEA线',
                                                               'formula': 'DEA(i,t) = EMA(DIF(i,t), 9)',
                                                               'required_fields': ['close_hfq'],
                                                               'module': 'src.factor.assets.factors.factors.moving_average_convergence_divergence.moving_average_convergence_divergence_signal_line_12_26_9',
                                                               'function': 'compute_moving_average_convergence_divergence_signal_line_12_26_9',
                                                               'output_columns': ['moving_average_convergence_divergence_signal_line_12_26_9']},
 'on_balance_volume': {'label': '能量潮指标OBV',
                       'formula': 'OBV(i,t) 按收盘涨跌方向对成交量进行累计加减',
                       'required_fields': ['close_hfq', 'vol'],
                       'module': 'src.factor.assets.factors.factors.on_balance_volume.on_balance_volume',
                       'function': 'compute_on_balance_volume',
                       'output_columns': ['on_balance_volume']},
 'parallel_line_difference_10_50': {'label': 'DFMA平行线差指标DIF',
                                    'formula': 'DFMA_DIF(i,t) = MA10(C,i,t) - MA50(C,i,t)',
                                    'required_fields': ['close_hfq'],
                                    'module': 'src.factor.assets.factors.factors.parallel_line_difference.parallel_line_difference_10_50',
                                    'function': 'compute_parallel_line_difference_10_50',
                                    'output_columns': ['parallel_line_difference_10_50']},
 'parallel_line_difference_average_10_50_10': {'label': 'DFMA平行线差指标DIFMA',
                                               'formula': 'DFMA_DIFMA(i,t) = MA10(DFMA_DIF,i,t)',
                                               'required_fields': ['close_hfq'],
                                               'module': 'src.factor.assets.factors.factors.parallel_line_difference.parallel_line_difference_average_10_50_10',
                                               'function': 'compute_parallel_line_difference_average_10_50_10',
                                               'output_columns': ['parallel_line_difference_average_10_50_10']},
 'ar_br_difference_26': {'label': 'ARBR差值指标',
                         'formula': 'ARBR(i,t) = AR(i,t) - BR(i,t)',
                         'required_fields': ['open_hfq', 'high_hfq', 'low_hfq', 'close_hfq'],
                         'module': 'src.domain.factor_formulas.popularity_willingness_index.ar_br_difference_26',
                         'function': 'compute_ar_br_difference_26',
                         'output_columns': ['ar_br_difference_26']},
 'ar_indicator_26': {'label': 'AR人气指标',
                     'formula': 'AR(i,t) = sum(H(i,t-k)-O(i,t-k), k=0..25) / sum(O(i,t-k)-L(i,t-k), k=0..25) * 100',
                     'required_fields': ['open_hfq', 'high_hfq', 'low_hfq', 'close_hfq'],
                     'module': 'src.domain.factor_formulas.popularity_willingness_index.ar_indicator_26',
                     'function': 'compute_ar_indicator_26',
                     'output_columns': ['ar_indicator_26']},
 'percentage_price_oscillator_12_26': {'label': '百分比价格振荡器PPO',
                                       'formula': 'PPO(i,t) = (EMA12(C,i,t) - EMA26(C,i,t)) / EMA26(C,i,t) * 100',
                                       'required_fields': ['close_hfq'],
                                       'module': 'src.domain.factor_formulas.percentage_price_oscillator.percentage_price_oscillator_12_26',
                                       'function': 'compute_percentage_price_oscillator_12_26',
                                       'output_columns': ['percentage_price_oscillator_12_26']},
 'price_linear_regression_coefficient_12': {'label': '价格线性回归系数PLRC',
                                            'formula': 'PLRC12(i,t): C(i,t-k)/mean(C(i,t-11),...,C(i,t)) = beta*T_k + '
                                                       'alpha, T_k=1..12',
                                            'required_fields': ['close_hfq'],
                                            'module': 'src.factor.assets.factors.factors.price_linear_regression_coefficient.price_linear_regression_coefficient_12',
                                            'function': 'compute_price_linear_regression_coefficient_12',
                                            'output_columns': ['price_linear_regression_coefficient_12']},
 'price_linear_regression_coefficient_24': {'label': '价格线性回归系数PLRC',
                                            'formula': 'PLRC24(i,t): C(i,t-k)/mean(C(i,t-23),...,C(i,t)) = beta*T_k + '
                                                       'alpha, T_k=1..24',
                                            'required_fields': ['close_hfq'],
                                            'module': 'src.factor.assets.factors.factors.price_linear_regression_coefficient.price_linear_regression_coefficient_24',
                                            'function': 'compute_price_linear_regression_coefficient_24',
                                            'output_columns': ['price_linear_regression_coefficient_24']},
 'price_linear_regression_coefficient_6': {'label': '价格线性回归系数PLRC',
                                           'formula': 'PLRC6(i,t): C(i,t-k)/mean(C(i,t-5),...,C(i,t)) = beta*T_k + '
                                                      'alpha, T_k=1..6',
                                           'required_fields': ['close_hfq'],
                                           'module': 'src.factor.assets.factors.factors.price_linear_regression_coefficient.price_linear_regression_coefficient_6',
                                           'function': 'compute_price_linear_regression_coefficient_6',
                                           'output_columns': ['price_linear_regression_coefficient_6']},
 'price_momentum_index_20': {'label': 'CR价格动量指标',
                             'formula': 'CR20(i,t) = sum(max(0,H(i,t-k)-MID(i,t-k-1)), k=0..19) / '
                                        'sum(max(0,MID(i,t-k-1)-L(i,t-k)), k=0..19) * 100, MID=(H+L)/2',
                             'required_fields': ['high_hfq', 'low_hfq'],
                             'module': 'src.factor.assets.factors.factors.price_momentum_index.price_momentum_index_20',
                             'function': 'compute_price_momentum_index_20',
                             'output_columns': ['price_momentum_index_20']},
 'psychological_line_12': {'label': 'PSY心理线指标',
                           'formula': 'PSY(i,t) = COUNT(C(i,t) > C(i,t-1), 12) / 12 * 100',
                           'required_fields': ['close_hfq'],
                           'module': 'src.factor.assets.factors.factors.psychological_line.psychological_line_12',
                           'function': 'compute_psychological_line_12',
                           'output_columns': ['psychological_line_12']},
 'psychological_line_average_12_6': {'label': 'PSY心理线平滑指标',
                                     'formula': 'PSYMA(i,t) = MA(PSY(i,t), 6)',
                                     'required_fields': ['close_hfq'],
                                     'module': 'src.factor.assets.factors.factors.psychological_line.psychological_line_average_12_6',
                                     'function': 'compute_psychological_line_average_12_6',
                                     'output_columns': ['psychological_line_average_12_6']},
 'quarterly_price_average_deviation_60': {'label': '三月均价偏离率',
                                          'formula': 'QuarterlyPriceAverageDeviation60(i,t) = C(i,t) / mean(C(i,t-59), '
                                                     '..., C(i,t)) - 1',
                                          'required_fields': ['close_hfq'],
                                          'module': 'src.factor.assets.factors.factors.quarterly_price_average_deviation.quarterly_price_average_deviation_60',
                                          'function': 'compute_quarterly_price_average_deviation_60',
                                          'output_columns': ['quarterly_price_average_deviation_60']},
 'rate_of_change_12': {'label': '变动率指标ROC',
                       'formula': 'ROC(i,t) = (C(i,t) - C(i,t-12)) / C(i,t-12) * 100',
                       'required_fields': ['close_hfq'],
                       'module': 'src.factor.assets.factors.factors.rate_of_change.rate_of_change_12',
                       'function': 'compute_rate_of_change_12',
                       'output_columns': ['rate_of_change_12']},
 'rate_of_change_120': {'label': '变动率指标ROC',
                        'formula': 'ROC120(i,t) = (C(i,t) - C(i,t-120)) / C(i,t-120) * 100',
                        'required_fields': ['close_hfq'],
                        'module': 'src.factor.assets.factors.factors.rate_of_change.rate_of_change_120',
                        'function': 'compute_rate_of_change_120',
                        'output_columns': ['rate_of_change_120']},
 'rate_of_change_20': {'label': '变动率指标ROC',
                       'formula': 'ROC20(i,t) = (C(i,t) - C(i,t-20)) / C(i,t-20) * 100',
                       'required_fields': ['close_hfq'],
                       'module': 'src.factor.assets.factors.factors.rate_of_change.rate_of_change_20',
                       'function': 'compute_rate_of_change_20',
                       'output_columns': ['rate_of_change_20']},
 'rate_of_change_6': {'label': '变动率指标ROC',
                      'formula': 'ROC6(i,t) = (C(i,t) - C(i,t-6)) / C(i,t-6) * 100',
                      'required_fields': ['close_hfq'],
                      'module': 'src.factor.assets.factors.factors.rate_of_change.rate_of_change_6',
                      'function': 'compute_rate_of_change_6',
                      'output_columns': ['rate_of_change_6']},
 'rate_of_change_60': {'label': '变动率指标ROC',
                       'formula': 'ROC60(i,t) = (C(i,t) - C(i,t-60)) / C(i,t-60) * 100',
                       'required_fields': ['close_hfq'],
                       'module': 'src.factor.assets.factors.factors.rate_of_change.rate_of_change_60',
                       'function': 'compute_rate_of_change_60',
                       'output_columns': ['rate_of_change_60']},
 'rate_of_change_average_12_6': {'label': '变动率指标平滑MAROC',
                                 'formula': 'MAROC(i,t) = MA(ROC(i,t), 6)',
                                 'required_fields': ['close_hfq'],
                                 'module': 'src.factor.assets.factors.factors.rate_of_change.rate_of_change_average_12_6',
                                 'function': 'compute_rate_of_change_average_12_6',
                                 'output_columns': ['rate_of_change_average_12_6']},
 'rate_of_change_percentage_10': {'label': '变动率百分比ROCP',
                                  'formula': 'ROCP10(i,t) = (C(i,t) - C(i,t-10)) / C(i,t-10)',
                                  'required_fields': ['close_hfq'],
                                  'module': 'src.domain.factor_formulas.rate_of_change.rate_of_change_percentage_10',
                                  'function': 'compute_rate_of_change_percentage_10',
                                  'output_columns': ['rate_of_change_percentage_10']},
 'rate_of_change_ratio_10': {'label': '变动率比值ROCR',
                             'formula': 'ROCR10(i,t) = C(i,t) / C(i,t-10)',
                             'required_fields': ['close_hfq'],
                             'module': 'src.domain.factor_formulas.rate_of_change.rate_of_change_ratio_10',
                             'function': 'compute_rate_of_change_ratio_10',
                             'output_columns': ['rate_of_change_ratio_10']},
 'rate_of_change_ratio_100_10': {'label': '百倍变动率比值ROCR100',
                                 'formula': 'ROCR10010(i,t) = C(i,t) / C(i,t-10) * 100',
                                 'required_fields': ['close_hfq'],
                                 'module': 'src.domain.factor_formulas.rate_of_change.rate_of_change_ratio_100_10',
                                 'function': 'compute_rate_of_change_ratio_100_10',
                                 'output_columns': ['rate_of_change_ratio_100_10']},
 'relative_strength_index_12': {'label': '相对强弱指标RSI',
                                'formula': 'RSI12(i,t) = SMA(MAX(C(i,t)-C(i,t-1),0),12,1) / '
                                           'SMA(ABS(C(i,t)-C(i,t-1)),12,1) * 100',
                                'required_fields': ['close_hfq'],
                                'module': 'src.factor.assets.factors.factors.relative_strength_index.relative_strength_index_12',
                                'function': 'compute_relative_strength_index_12',
                                'output_columns': ['relative_strength_index_12']},
 'relative_strength_index_24': {'label': '相对强弱指标RSI',
                                'formula': 'RSI24(i,t) = SMA(MAX(C(i,t)-C(i,t-1),0),24,1) / '
                                           'SMA(ABS(C(i,t)-C(i,t-1)),24,1) * 100',
                                'required_fields': ['close_hfq'],
                                'module': 'src.factor.assets.factors.factors.relative_strength_index.relative_strength_index_24',
                                'function': 'compute_relative_strength_index_24',
                                'output_columns': ['relative_strength_index_24']},
 'relative_strength_index_6': {'label': '相对强弱指标RSI',
                               'formula': 'RSI6(i,t) = SMA(MAX(C(i,t)-C(i,t-1),0),6,1) / SMA(ABS(C(i,t)-C(i,t-1)),6,1) '
                                          '* 100',
                               'required_fields': ['close_hfq'],
                               'module': 'src.factor.assets.factors.factors.relative_strength_index.relative_strength_index_6',
                               'function': 'compute_relative_strength_index_6',
                               'output_columns': ['relative_strength_index_6']},
 'return_kurtosis_120': {'label': '收益峰度',
                         'formula': 'Kurtosis120(i,t) = kurtosis(C(i,t-k)/C(i,t-k-1)-1, k=0..119)',
                         'required_fields': ['close_hfq'],
                         'module': 'src.factor.assets.factors.factors.return_kurtosis.return_kurtosis_120',
                         'function': 'compute_return_kurtosis_120',
                         'output_columns': ['return_kurtosis_120']},
 'return_kurtosis_20': {'label': '收益峰度',
                        'formula': 'Kurtosis20(i,t) = kurtosis(C(i,t-k)/C(i,t-k-1)-1, k=0..19)',
                        'required_fields': ['close_hfq'],
                        'module': 'src.factor.assets.factors.factors.return_kurtosis.return_kurtosis_20',
                        'function': 'compute_return_kurtosis_20',
                        'output_columns': ['return_kurtosis_20']},
 'return_kurtosis_60': {'label': '收益峰度',
                        'formula': 'Kurtosis60(i,t) = kurtosis(C(i,t-k)/C(i,t-k-1)-1, k=0..59)',
                        'required_fields': ['close_hfq'],
                        'module': 'src.factor.assets.factors.factors.return_kurtosis.return_kurtosis_60',
                        'function': 'compute_return_kurtosis_60',
                        'output_columns': ['return_kurtosis_60']},
 'return_skewness_120': {'label': '收益偏度',
                         'formula': 'Skewness120(i,t) = skew(C(i,t-k)/C(i,t-k-1)-1, k=0..119)',
                         'required_fields': ['close_hfq'],
                         'module': 'src.factor.assets.factors.factors.return_skewness.return_skewness_120',
                         'function': 'compute_return_skewness_120',
                         'output_columns': ['return_skewness_120']},
 'return_skewness_20': {'label': '收益偏度',
                        'formula': 'Skewness20(i,t) = skew(C(i,t-k)/C(i,t-k-1)-1, k=0..19)',
                        'required_fields': ['close_hfq'],
                        'module': 'src.factor.assets.factors.factors.return_skewness.return_skewness_20',
                        'function': 'compute_return_skewness_20',
                        'output_columns': ['return_skewness_20']},
 'return_skewness_60': {'label': '收益偏度',
                        'formula': 'Skewness60(i,t) = skew(C(i,t-k)/C(i,t-k-1)-1, k=0..59)',
                        'required_fields': ['close_hfq'],
                        'module': 'src.factor.assets.factors.factors.return_skewness.return_skewness_60',
                        'function': 'compute_return_skewness_60',
                        'output_columns': ['return_skewness_60']},
 'return_variance_120': {'label': '收益方差',
                         'formula': 'Variance120(i,t) = var(C(i,t-k)/C(i,t-k-1)-1, k=0..119)',
                         'required_fields': ['close_hfq'],
                         'module': 'src.factor.assets.factors.factors.return_variance.return_variance_120',
                         'function': 'compute_return_variance_120',
                         'output_columns': ['return_variance_120']},
 'return_variance_20': {'label': '收益方差',
                        'formula': 'Variance20(i,t) = var(C(i,t-k)/C(i,t-k-1)-1, k=0..19)',
                        'required_fields': ['close_hfq'],
                        'module': 'src.factor.assets.factors.factors.return_variance.return_variance_20',
                        'function': 'compute_return_variance_20',
                        'output_columns': ['return_variance_20']},
 'return_variance_60': {'label': '收益方差',
                        'formula': 'Variance60(i,t) = var(C(i,t-k)/C(i,t-k-1)-1, k=0..59)',
                        'required_fields': ['close_hfq'],
                        'module': 'src.factor.assets.factors.factors.return_variance.return_variance_60',
                        'function': 'compute_return_variance_60',
                        'output_columns': ['return_variance_60']},
 'simple_moving_average_10': {'label': '简单移动平均MA',
                              'formula': 'MA10(i,t) = mean(C(i,t-9), ..., C(i,t))',
                              'required_fields': ['close_hfq'],
                              'module': 'src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_10',
                              'function': 'compute_simple_moving_average_10',
                              'output_columns': ['simple_moving_average_10']},
 'simple_moving_average_20': {'label': '简单移动平均MA',
                              'formula': 'MA20(i,t) = mean(C(i,t-19), ..., C(i,t))',
                              'required_fields': ['close_hfq'],
                              'module': 'src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_20',
                              'function': 'compute_simple_moving_average_20',
                              'output_columns': ['simple_moving_average_20']},
 'simple_moving_average_250': {'label': '简单移动平均MA',
                               'formula': 'MA250(i,t) = mean(C(i,t-249), ..., C(i,t))',
                               'required_fields': ['close_hfq'],
                               'module': 'src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_250',
                               'function': 'compute_simple_moving_average_250',
                               'output_columns': ['simple_moving_average_250']},
 'simple_moving_average_30': {'label': '简单移动平均MA',
                              'formula': 'MA30(i,t) = mean(C(i,t-29), ..., C(i,t))',
                              'required_fields': ['close_hfq'],
                              'module': 'src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_30',
                              'function': 'compute_simple_moving_average_30',
                              'output_columns': ['simple_moving_average_30']},
 'simple_moving_average_5': {'label': '简单移动平均MA',
                             'formula': 'MA5(i,t) = mean(C(i,t-4), ..., C(i,t))',
                             'required_fields': ['close_hfq'],
                             'module': 'src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_5',
                             'function': 'compute_simple_moving_average_5',
                             'output_columns': ['simple_moving_average_5']},
 'simple_moving_average_60': {'label': '简单移动平均MA',
                              'formula': 'MA60(i,t) = mean(C(i,t-59), ..., C(i,t))',
                              'required_fields': ['close_hfq'],
                              'module': 'src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_60',
                              'function': 'compute_simple_moving_average_60',
                              'output_columns': ['simple_moving_average_60']},
 'simple_moving_average_90': {'label': '简单移动平均MA',
                              'formula': 'MA90(i,t) = mean(C(i,t-89), ..., C(i,t))',
                              'required_fields': ['close_hfq'],
                              'module': 'src.factor.assets.factors.factors.simple_moving_average.simple_moving_average_90',
                              'function': 'compute_simple_moving_average_90',
                              'output_columns': ['simple_moving_average_90']},
 'single_day_volume_price_trend': {'label': '单日价量趋势VPT',
                                   'formula': 'SingleDayVPT(i,t) = (C(i,t) - C(i,t-1)) / C(i,t-1) * VOL(i,t)',
                                   'required_fields': ['close_hfq', 'vol'],
                                   'module': 'src.factor.assets.factors.factors.single_day_volume_price_trend.single_day_volume_price_trend',
                                   'function': 'compute_single_day_volume_price_trend',
                                   'output_columns': ['single_day_volume_price_trend']},
 'single_day_volume_price_trend_average_12': {'label': '单日价量趋势均值VPT',
                                              'formula': 'SingleDayVPT_MA12(i,t) = MA(SingleDayVPT(i,t), 12)',
                                              'required_fields': ['close_hfq', 'vol'],
                                              'module': 'src.factor.assets.factors.factors.single_day_volume_price_trend.single_day_volume_price_trend_average_12',
                                              'function': 'compute_single_day_volume_price_trend_average_12',
                                              'output_columns': ['single_day_volume_price_trend_average_12']},
 'single_day_volume_price_trend_average_6': {'label': '单日价量趋势均值VPT',
                                             'formula': 'SingleDayVPT_MA6(i,t) = MA(SingleDayVPT(i,t), 6)',
                                             'required_fields': ['close_hfq', 'vol'],
                                             'module': 'src.factor.assets.factors.factors.single_day_volume_price_trend.single_day_volume_price_trend_average_6',
                                             'function': 'compute_single_day_volume_price_trend_average_6',
                                             'output_columns': ['single_day_volume_price_trend_average_6']},
 'stochastic_d_line_9_3_3': {'label': 'KDJ指标D线',
                             'formula': 'D(i,t) = 2/3 * D(i,t-1) + 1/3 * K(i,t)',
                             'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                             'module': 'src.factor.assets.factors.factors.stochastic_oscillator.stochastic_d_line_9_3_3',
                             'function': 'compute_stochastic_d_line_9_3_3',
                             'output_columns': ['stochastic_d_line_9_3_3']},
 'stochastic_fast_d_line_5_3': {'label': '快速随机指标FASTD',
                                'formula': 'FASTD(i,t) = MA(FASTK(i,t), 3), FASTK 基于 5 日最高最低区间',
                                'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                'module': 'src.domain.factor_formulas.stochastic_oscillator.stochastic_fast_d_line_5_3',
                                'function': 'compute_stochastic_fast_d_line_5_3',
                                'output_columns': ['stochastic_fast_d_line_5_3']},
 'stochastic_fast_k_line_5_3': {'label': '快速随机指标FASTK',
                                'formula': 'FASTK(i,t) = (C(i,t)-LLV(L,5)) / (HHV(H,5)-LLV(L,5)) * 100',
                                'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                'module': 'src.domain.factor_formulas.stochastic_oscillator.stochastic_fast_k_line_5_3',
                                'function': 'compute_stochastic_fast_k_line_5_3',
                                'output_columns': ['stochastic_fast_k_line_5_3']},
 'stochastic_j_line_9_3_3': {'label': 'KDJ指标J线',
                             'formula': 'KDJ(i,t) = 3 * K(i,t) - 2 * D(i,t)',
                             'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                             'module': 'src.factor.assets.factors.factors.stochastic_oscillator.stochastic_j_line_9_3_3',
                             'function': 'compute_stochastic_j_line_9_3_3',
                             'output_columns': ['stochastic_j_line_9_3_3']},
 'stochastic_k_line_9_3_3': {'label': 'KDJ指标K线',
                             'formula': 'K(i,t) = 2/3 * K(i,t-1) + 1/3 * RSV(i,t)',
                             'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                             'module': 'src.factor.assets.factors.factors.stochastic_oscillator.stochastic_k_line_9_3_3',
                             'function': 'compute_stochastic_k_line_9_3_3',
                             'output_columns': ['stochastic_k_line_9_3_3']},
 'stochastic_relative_strength_index_fast_d_14_5_3': {'label': '随机相对强弱指标FASTD',
                                                       'formula': 'STOCHRSI_FASTD(i,t) = MA(STOCHRSI_FASTK(i,t), 3), STOCHRSI_FASTK 基于 14 日 RSI 的 5 日随机化',
                                                       'required_fields': ['close_hfq'],
                                                       'module': 'src.domain.factor_formulas.stochastic_oscillator.stochastic_relative_strength_index_fast_d_14_5_3',
                                                       'function': 'compute_stochastic_relative_strength_index_fast_d_14_5_3',
                                                       'output_columns': ['stochastic_relative_strength_index_fast_d_14_5_3']},
 'stochastic_relative_strength_index_fast_k_14_5_3': {'label': '随机相对强弱指标FASTK',
                                                       'formula': 'STOCHRSI_FASTK(i,t) = (RSI14(i,t)-LLV(RSI14,5)) / (HHV(RSI14,5)-LLV(RSI14,5)) * 100',
                                                       'required_fields': ['close_hfq'],
                                                       'module': 'src.domain.factor_formulas.stochastic_oscillator.stochastic_relative_strength_index_fast_k_14_5_3',
                                                       'function': 'compute_stochastic_relative_strength_index_fast_k_14_5_3',
                                                       'output_columns': ['stochastic_relative_strength_index_fast_k_14_5_3']},
 'triple_exponential_oscillator_12': {'label': '三重指数平滑平均线TRIX',
                                      'formula': 'TRIX(i,t) = (EMA3(i,t) - EMA3(i,t-1)) / EMA3(i,t-1) * 100',
                                      'required_fields': ['close_hfq'],
                                      'module': 'src.factor.assets.factors.factors.triple_exponential_oscillator.triple_exponential_oscillator_12',
                                      'function': 'compute_triple_exponential_oscillator_12',
                                      'output_columns': ['triple_exponential_oscillator_12']},
 'triple_exponential_oscillator_5_10_5': {'label': '三重指数平滑平均线TRIX',
                                          'formula': 'TRIX(i,t) = (MTR(i,t) - MTR(i,t-1)) / MTR(i,t-1) * 100, '
                                                     'MTR=EMA(EMA(EMA(C,5),10),5)',
                                          'required_fields': ['close_hfq'],
                                          'module': 'src.factor.assets.factors.factors.triple_exponential_oscillator.triple_exponential_oscillator_5_10_5',
                                          'function': 'compute_triple_exponential_oscillator_5_10_5',
                                          'output_columns': ['triple_exponential_oscillator_5_10_5']},
 'triple_exponential_oscillator_average_12_20': {'label': '三重指数平滑平均线TRMA',
                                                 'formula': 'TRMA(i,t) = MA(TRIX(i,t), 20)',
                                                 'required_fields': ['close_hfq'],
                                                 'module': 'src.factor.assets.factors.factors.triple_exponential_oscillator.triple_exponential_oscillator_average_12_20',
                                                 'function': 'compute_triple_exponential_oscillator_average_12_20',
                                                 'output_columns': ['triple_exponential_oscillator_average_12_20']},
 'turnover_rate_ratio_10_120': {'label': '平均换手率比值DAVOL',
                                'formula': 'DAVOL10(i,t) = mean(turnover_rate(i,t-9), ..., turnover_rate(i,t)) / '
                                           'mean(turnover_rate(i,t-119), ..., turnover_rate(i,t))',
                                'required_fields': ['turnover_rate'],
                                'module': 'src.factor.assets.factors.factors.turnover_rate_ratio.turnover_rate_ratio_10_120',
                                'function': 'compute_turnover_rate_ratio_10_120',
                                'output_columns': ['turnover_rate_ratio_10_120']},
 'turnover_rate_ratio_20_120': {'label': '平均换手率比值DAVOL',
                                'formula': 'DAVOL20(i,t) = mean(turnover_rate(i,t-19), ..., turnover_rate(i,t)) / '
                                           'mean(turnover_rate(i,t-119), ..., turnover_rate(i,t))',
                                'required_fields': ['turnover_rate'],
                                'module': 'src.factor.assets.factors.factors.turnover_rate_ratio.turnover_rate_ratio_20_120',
                                'function': 'compute_turnover_rate_ratio_20_120',
                                'output_columns': ['turnover_rate_ratio_20_120']},
 'turnover_rate_ratio_60_120': {'label': '平均换手率比值DAVOL',
                                'formula': 'DAVOL60(i,t) = mean(turnover_rate(i,t-59), ..., turnover_rate(i,t)) / '
                                           'mean(turnover_rate(i,t-119), ..., turnover_rate(i,t))',
                                'required_fields': ['turnover_rate'],
                                'module': 'src.factor.assets.factors.factors.turnover_rate_ratio.turnover_rate_ratio_60_120',
                                'function': 'compute_turnover_rate_ratio_60_120',
                                'output_columns': ['turnover_rate_ratio_60_120']},
 'turnover_value_standard_deviation_20': {'label': '成交金额标准差TVSTD',
                                          'formula': 'TVSTD20(i,t) = std(AMOUNT(i,t-19), ..., AMOUNT(i,t))',
                                          'required_fields': ['amount'],
                                          'module': 'src.factor.assets.factors.factors.turnover_value_standard_deviation.turnover_value_standard_deviation_20',
                                          'function': 'compute_turnover_value_standard_deviation_20',
                                          'output_columns': ['turnover_value_standard_deviation_20']},
 'ultimate_oscillator_7_14_28': {'label': '终极振荡指标ULTOSC',
                                 'formula': 'ULTOSC(i,t) = 100 * (4*A7(i,t) + 2*A14(i,t) + A28(i,t)) / 7, A_N=sum(BP,N)/sum(TR,N)',
                                 'required_fields': ['high_hfq', 'low_hfq', 'close_hfq'],
                                 'module': 'src.domain.factor_formulas.ultimate_oscillator.ultimate_oscillator_7_14_28',
                                 'function': 'compute_ultimate_oscillator_7_14_28',
                                 'output_columns': ['ultimate_oscillator_7_14_28']},
 'turnover_value_standard_deviation_6': {'label': '成交金额标准差TVSTD',
                                         'formula': 'TVSTD6(i,t) = std(AMOUNT(i,t-5), ..., AMOUNT(i,t))',
                                         'required_fields': ['amount'],
                                         'module': 'src.factor.assets.factors.factors.turnover_value_standard_deviation.turnover_value_standard_deviation_6',
                                         'function': 'compute_turnover_value_standard_deviation_6',
                                         'output_columns': ['turnover_value_standard_deviation_6']},
 'volume_ratio_26': {'label': 'VR容量比率',
                     'formula': 'VR(i,t) = (SUM(AV,26) + 0.5 * SUM(CV,26)) / (SUM(BV,26) + 0.5 * SUM(CV,26)) * 100',
                     'required_fields': ['close_hfq', 'vol'],
                     'module': 'src.factor.assets.factors.factors.volume_ratio.volume_ratio_26',
                     'function': 'compute_volume_ratio_26',
                     'output_columns': ['volume_ratio_26']},
 'volume_return_interaction_20': {'label': '量价收益交互Volume1M',
                                  'formula': 'Volume1M(i,t) = VOL(i,t) / mean(VOL(i,t-19),...,VOL(i,t)) * '
                                             'mean(R(i,t-19),...,R(i,t))',
                                  'required_fields': ['close_hfq', 'vol'],
                                  'module': 'src.factor.assets.factors.factors.volume_return_interaction.volume_return_interaction_20',
                                  'function': 'compute_volume_return_interaction_20',
                                  'output_columns': ['volume_return_interaction_20']},
 'volume_standard_deviation_10': {'label': '成交量标准差VSTD',
                                  'formula': 'VSTD10(i,t) = std(VOL(i,t-9), ..., VOL(i,t))',
                                  'required_fields': ['vol'],
                                  'module': 'src.factor.assets.factors.factors.volume_standard_deviation.volume_standard_deviation_10',
                                  'function': 'compute_volume_standard_deviation_10',
                                  'output_columns': ['volume_standard_deviation_10']},
 'volume_standard_deviation_20': {'label': '成交量标准差VSTD',
                                  'formula': 'VSTD20(i,t) = std(VOL(i,t-19), ..., VOL(i,t))',
                                  'required_fields': ['vol'],
                                  'module': 'src.factor.assets.factors.factors.volume_standard_deviation.volume_standard_deviation_20',
                                  'function': 'compute_volume_standard_deviation_20',
                                  'output_columns': ['volume_standard_deviation_20']},
 'williams_percent_range_10': {'label': 'W&R威廉指标',
                               'formula': 'WR10(i,t) = (HHV(H,10) - C(i,t)) / (HHV(H,10) - LLV(L,10)) * 100',
                               'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                               'module': 'src.factor.assets.factors.factors.williams_percent_range.williams_percent_range_10',
                               'function': 'compute_williams_percent_range_10',
                               'output_columns': ['williams_percent_range_10']},
 'williams_percent_range_6': {'label': 'W&R威廉指标',
                              'formula': 'WR6(i,t) = (HHV(H,6) - C(i,t)) / (HHV(H,6) - LLV(L,6)) * 100',
                              'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                              'module': 'src.factor.assets.factors.factors.williams_percent_range.williams_percent_range_6',
                              'function': 'compute_williams_percent_range_6',
                              'output_columns': ['williams_percent_range_6']},
 'williams_variable_accumulation_distribution_6': {'label': '威廉变异离散量WVAD',
                                                   'formula': 'WVAD(i,t) = '
                                                              'sum((C(i,t-k)-O(i,t-k))/(H(i,t-k)-L(i,t-k))*VOL(i,t-k), '
                                                              'k=0..5)',
                                                   'required_fields': ['open_hfq',
                                                                       'high_hfq',
                                                                       'low_hfq',
                                                                       'close_hfq',
                                                                       'vol'],
                                                   'module': 'src.factor.assets.factors.factors.williams_variable_accumulation_distribution.williams_variable_accumulation_distribution_6',
                                                   'function': 'compute_williams_variable_accumulation_distribution_6',
                                                   'output_columns': ['williams_variable_accumulation_distribution_6']},
 'williams_variable_accumulation_distribution_average_6_6': {'label': '威廉变异离散量均值MAWVAD',
                                                             'formula': 'MAWVAD(i,t) = mean(WVAD(i,t-5), ..., '
                                                                        'WVAD(i,t))',
                                                             'required_fields': ['open_hfq',
                                                                                 'high_hfq',
                                                                                 'low_hfq',
                                                                                 'close_hfq',
                                                                                 'vol'],
                                                             'module': 'src.factor.assets.factors.factors.williams_variable_accumulation_distribution.williams_variable_accumulation_distribution_average_6_6',
                                                             'function': 'compute_williams_variable_accumulation_distribution_average_6_6',
                                                             'output_columns': ['williams_variable_accumulation_distribution_average_6_6']},
 'br_indicator_26': {'label': 'BR意愿指标',
                     'formula': 'BR(i,t) = sum(max(0,H(i,t-k)-C(i,t-k-1)), k=0..25) / '
                                'sum(max(0,C(i,t-k-1)-L(i,t-k)), k=0..25) * 100',
                     'required_fields': ['open_hfq', 'high_hfq', 'low_hfq', 'close_hfq'],
                     'module': 'src.domain.factor_formulas.popularity_willingness_index.br_indicator_26',
                     'function': 'compute_br_indicator_26',
                     'output_columns': ['br_indicator_26']},
 'xue_si_channel_ii_line_1_102_7': {'label': '薛斯通道II 通道1',
                                    'formula': 'XSII_TD1(i,t) = MA((2*C(i,t)+H(i,t)+L(i,t))/4, 5) * 102 / 100',
                                    'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                    'module': 'src.factor.assets.factors.factors.xue_si_channel_ii.xue_si_channel_ii_line_1_102_7',
                                    'function': 'compute_xue_si_channel_ii_line_1_102_7',
                                    'output_columns': ['xue_si_channel_ii_line_1_102_7']},
 'xue_si_channel_ii_line_2_102_7': {'label': '薛斯通道II 通道2',
                                    'formula': 'XSII_TD2(i,t) = MA((2*C(i,t)+H(i,t)+L(i,t))/4, 5) * 98 / 100',
                                    'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                    'module': 'src.factor.assets.factors.factors.xue_si_channel_ii.xue_si_channel_ii_line_2_102_7',
                                    'function': 'compute_xue_si_channel_ii_line_2_102_7',
                                    'output_columns': ['xue_si_channel_ii_line_2_102_7']},
 'xue_si_channel_ii_line_3_102_7': {'label': '薛斯通道II 通道3',
                                    'formula': 'XSII_TD3(i,t) = (1 + 7/100) * DMA(C(i,t), '
                                               'ABS((2*C(i,t)+H(i,t)+L(i,t))/4 - MA(C(i,t),20)) / MA(C(i,t),20))',
                                    'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                    'module': 'src.factor.assets.factors.factors.xue_si_channel_ii.xue_si_channel_ii_line_3_102_7',
                                    'function': 'compute_xue_si_channel_ii_line_3_102_7',
                                    'output_columns': ['xue_si_channel_ii_line_3_102_7']},
 'xue_si_channel_ii_line_4_102_7': {'label': '薛斯通道II 通道4',
                                    'formula': 'XSII_TD4(i,t) = (1 - 7/100) * DMA(C(i,t), '
                                               'ABS((2*C(i,t)+H(i,t)+L(i,t))/4 - MA(C(i,t),20)) / MA(C(i,t),20))',
                                    'required_fields': ['close_hfq', 'high_hfq', 'low_hfq'],
                                    'module': 'src.factor.assets.factors.factors.xue_si_channel_ii.xue_si_channel_ii_line_4_102_7',
                                    'function': 'compute_xue_si_channel_ii_line_4_102_7',
                                    'output_columns': ['xue_si_channel_ii_line_4_102_7']}}

FACTOR_PARAMETERS = {'accumulation_distribution_line': {},
 'accumulation_swing_index_26': {'N': 26},
 'accumulation_swing_index_average_26_10': {'N': 26, 'M': 10},
 'chaikin_accumulation_distribution_oscillator_3_10': {'SHORT': 3, 'LONG': 10},
 'annual_price_average_deviation_250': {'N': 250},
 'annual_price_rank_position_250': {'N': 250},
 'arron_down_25': {'N': 25},
 'arron_oscillator_25': {'N': 25},
 'arron_up_25': {'N': 25},
 'average_directional_index_14_6': {'M1': 14, 'M2': 6},
 'average_directional_index_rating_14_6': {'M1': 14, 'M2': 6},
 'average_price_hlc': {},
 'average_price_ohlc': {},
 'balance_of_power': {},
 'average_true_range_14': {'N': 14},
 'average_true_range_20': {'N': 20},
 'average_true_range_6': {'N': 6},
 'average_turnover_rate_10': {'N': 10},
 'average_turnover_rate_120': {'N': 120},
 'average_turnover_rate_20': {'N': 20},
 'average_turnover_rate_240': {'N': 240},
 'average_turnover_rate_5': {'N': 5},
 'average_turnover_rate_60': {'N': 60},
 'bear_power_13': {'N': 13},
 'bias_ratio_12': {'N': 12},
 'bias_ratio_24': {'N': 24},
 'bias_ratio_6': {'N': 6},
 'bias_ratio_60': {'N': 60},
 'bollinger_lower_band_20_2': {'N': 20, 'P': 2},
 'bollinger_middle_band_20_2': {'N': 20, 'P': 2},
 'bollinger_upper_band_20_2': {'N': 20, 'P': 2},
 'bull_and_bear_index_3_6_12_21': {'M1': 3, 'M2': 6, 'M3': 12, 'M4': 21},
 'bull_and_bear_index_momentum_3_6_12_24': {'M1': 3, 'M2': 6, 'M3': 12, 'M4': 24},
 'bull_power_13': {'N': 13},
'chande_momentum_oscillator_14': {'N': 14},
'commodity_channel_index_10': {'N': 10},
 'commodity_channel_index_120': {'N': 120},
 'commodity_channel_index_14': {'N': 14},
 'commodity_channel_index_20': {'N': 20},
 'commodity_channel_index_60': {'N': 60},
 'consecutive_down_days': {},
 'consecutive_up_days': {},
 'detrended_price_oscillator_20_10': {'M1': 20, 'M2': 10},
 'detrended_price_oscillator_average_20_10_6': {'M1': 20, 'M2': 10, 'M3': 6},
 'directional_movement_negative_indicator_14': {'M1': 14},
 'directional_movement_positive_indicator_14': {'M1': 14},
 'directional_movement_index_14': {'M1': 14},
 'double_exponential_moving_average_10': {'N': 10},
 'double_exponential_moving_average_20': {'N': 20},
 'double_exponential_moving_average_60': {'N': 60},
 'donchian_channel_lower_band_20': {'N': 20},
 'donchian_channel_middle_band_20': {'N': 20},
 'donchian_channel_upper_band_20': {'N': 20},
 'ease_of_movement_average_14_9': {'N': 14, 'M': 9},
 'ease_of_movement_value_14': {'N': 14},
 'exponential_average_12': {'N1': 12},
 'exponential_average_50': {'N2': 50},
 'exponential_moving_average_10': {'N': 10},
 'exponential_moving_average_20': {'N': 20},
 'exponential_moving_average_250': {'N': 250},
 'exponential_moving_average_30': {'N': 30},
 'exponential_moving_average_5': {'N': 5},
 'exponential_moving_average_60': {'N': 60},
 'exponential_moving_average_90': {'N': 90},
 'keltner_channel_lower_band_20_10': {'N': 20, 'M': 10},
 'keltner_channel_middle_band_20_10': {'N': 20, 'M': 10},
 'keltner_channel_upper_band_20_10': {'N': 20, 'M': 10},
 'kaufman_adaptive_moving_average_10_2_30': {'ER': 10, 'FAST': 2, 'SLOW': 30},
 'mass_index_9_25': {'N1': 9, 'N2': 25},
 'mass_index_average_9_25_6': {'N1': 9, 'N2': 25, 'M': 6},
 'momentum_12': {'N': 12},
 'momentum_average_12_6': {'N': 12, 'M': 6},
 'minus_directional_movement_14': {'M1': 14},
 'plus_directional_movement_14': {'M1': 14},
 'money_flow_20': {'N': 20},
 'money_flow_index_14': {'N': 14},
 'monthly_price_average_deviation_20': {'N': 20},
 'monthly_return_rank_score_20': {'N': 20},
 'moving_average_convergence_divergence_difference_line_12_26_9': {'SHORT': 12, 'LONG': 26, 'M': 9},
 'moving_average_convergence_divergence_histogram_12_26_9': {'SHORT': 12, 'LONG': 26, 'M': 9},
 'moving_average_convergence_divergence_signal_line_12_26_9': {'SHORT': 12, 'LONG': 26, 'M': 9},
 'on_balance_volume': {},
 'parallel_line_difference_10_50': {'N1': 10, 'N2': 50},
 'parallel_line_difference_average_10_50_10': {'N1': 10, 'N2': 50, 'M': 10},
 'ar_br_difference_26': {'M1': 26},
 'ar_indicator_26': {'M1': 26},
 'percentage_price_oscillator_12_26': {'SHORT': 12, 'LONG': 26},
 'price_linear_regression_coefficient_12': {'N': 12},
 'price_linear_regression_coefficient_24': {'N': 24},
 'price_linear_regression_coefficient_6': {'N': 6},
 'price_momentum_index_20': {'N': 20},
 'psychological_line_12': {'N': 12},
 'psychological_line_average_12_6': {'N': 12, 'M': 6},
 'quarterly_price_average_deviation_60': {'N': 60},
 'rate_of_change_12': {'N': 12},
 'rate_of_change_120': {'N': 120},
 'rate_of_change_20': {'N': 20},
 'rate_of_change_6': {'N': 6},
 'rate_of_change_60': {'N': 60},
 'rate_of_change_average_12_6': {'N': 12, 'M': 6},
 'rate_of_change_percentage_10': {'N': 10},
 'rate_of_change_ratio_10': {'N': 10},
 'rate_of_change_ratio_100_10': {'N': 10},
 'relative_strength_index_12': {'N': 12},
 'relative_strength_index_24': {'N': 24},
 'relative_strength_index_6': {'N': 6},
 'return_kurtosis_120': {'N': 120},
 'return_kurtosis_20': {'N': 20},
 'return_kurtosis_60': {'N': 60},
 'return_skewness_120': {'N': 120},
 'return_skewness_20': {'N': 20},
 'return_skewness_60': {'N': 60},
 'return_variance_120': {'N': 120},
 'return_variance_20': {'N': 20},
 'return_variance_60': {'N': 60},
 'simple_moving_average_10': {'N': 10},
 'simple_moving_average_20': {'N': 20},
 'simple_moving_average_250': {'N': 250},
 'simple_moving_average_30': {'N': 30},
 'simple_moving_average_5': {'N': 5},
 'simple_moving_average_60': {'N': 60},
 'simple_moving_average_90': {'N': 90},
 'single_day_volume_price_trend': {},
 'single_day_volume_price_trend_average_12': {'N': 12},
 'single_day_volume_price_trend_average_6': {'N': 6},
 'stochastic_d_line_9_3_3': {'N': 9, 'M1': 3, 'M2': 3},
 'stochastic_fast_d_line_5_3': {'N': 5, 'M': 3},
 'stochastic_fast_k_line_5_3': {'N': 5, 'M': 3},
 'stochastic_j_line_9_3_3': {'N': 9, 'M1': 3, 'M2': 3},
 'stochastic_k_line_9_3_3': {'N': 9, 'M1': 3, 'M2': 3},
 'stochastic_relative_strength_index_fast_d_14_5_3': {'RSI_N': 14, 'N': 5, 'M': 3},
 'stochastic_relative_strength_index_fast_k_14_5_3': {'RSI_N': 14, 'N': 5, 'M': 3},
 'triple_exponential_oscillator_12': {'M1': 12},
 'triple_exponential_oscillator_5_10_5': {'M1': 5, 'M2': 10, 'M3': 5},
 'triple_exponential_oscillator_average_12_20': {'M1': 12, 'M2': 20},
 'turnover_rate_ratio_10_120': {'N1': 10, 'N2': 120},
 'turnover_rate_ratio_20_120': {'N1': 20, 'N2': 120},
 'turnover_rate_ratio_60_120': {'N1': 60, 'N2': 120},
 'turnover_value_standard_deviation_20': {'N': 20},
 'ultimate_oscillator_7_14_28': {'N1': 7, 'N2': 14, 'N3': 28},
 'turnover_value_standard_deviation_6': {'N': 6},
 'volume_ratio_26': {'M1': 26},
 'volume_return_interaction_20': {'N': 20},
 'volume_standard_deviation_10': {'N': 10},
 'volume_standard_deviation_20': {'N': 20},
 'williams_percent_range_10': {'N': 10},
 'williams_percent_range_6': {'N': 6},
 'williams_variable_accumulation_distribution_6': {'N': 6},
 'williams_variable_accumulation_distribution_average_6_6': {'N': 6, 'M': 6},
 'br_indicator_26': {'M1': 26},
 'xue_si_channel_ii_line_1_102_7': {'N': 102, 'M': 7},
 'xue_si_channel_ii_line_2_102_7': {'N': 102, 'M': 7},
 'xue_si_channel_ii_line_3_102_7': {'N': 102, 'M': 7},
 'xue_si_channel_ii_line_4_102_7': {'N': 102, 'M': 7}}
